/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class CalcTable extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 709518038;

	/**
	 * The singleton instance of calc
	 */
	public static final CalcTable CALC = new CalcTable();

	/**
	 * No further instances allowed
	 */
	private CalcTable() {
		super("calc");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			org.openforis.calc.persistence.jooq.Sequences.AOI_HIERARCHY_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.AOI_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.CATEGORY_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.CLUSTER_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.OBSERVATION_UNIT_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.OPERATION_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.OPERATION_PARAMETER_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.PLOT_CATEGORY_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.PLOT_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.PLOT_MEASUREMENT_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.PLOT_SURVEY_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.PROCESS_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.PROCESSING_CHAIN_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.SPECIMEN_CATEGORY_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.SPECIMEN_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.SPECIMEN_MEASUREMENT_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.STRATUM_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.SURVEY_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.TAXON_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.TAXONOMIC_CHECKLIST_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.TAXON_VERNACULAR_NAME_ID_SEQ,
			org.openforis.calc.persistence.jooq.Sequences.VARIABLE_ID_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.openforis.calc.persistence.jooq.tables.AoiTable.AOI,
			org.openforis.calc.persistence.jooq.tables.AoiHierarchyTable.AOI_HIERARCHY,
			org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY,
			org.openforis.calc.persistence.jooq.tables.ClusterTable.CLUSTER,
			org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW,
			org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT,
			org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION,
			org.openforis.calc.persistence.jooq.tables.OperationParameterTable.OPERATION_PARAMETER,
			org.openforis.calc.persistence.jooq.tables.PlotTable.PLOT,
			org.openforis.calc.persistence.jooq.tables.PlotCategoryTable.PLOT_CATEGORY,
			org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW,
			org.openforis.calc.persistence.jooq.tables.PlotMeasurementTable.PLOT_MEASUREMENT,
			org.openforis.calc.persistence.jooq.tables.PlotMeasurementViewTable.PLOT_MEASUREMENT_VIEW,
			org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY,
			org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW,
			org.openforis.calc.persistence.jooq.tables.PlotViewTable.PLOT_VIEW,
			org.openforis.calc.persistence.jooq.tables.ProcessTable.PROCESS,
			org.openforis.calc.persistence.jooq.tables.ProcessingChainTable.PROCESSING_CHAIN,
			org.openforis.calc.persistence.jooq.tables.SpecimenTable.SPECIMEN,
			org.openforis.calc.persistence.jooq.tables.SpecimenCategoryTable.SPECIMEN_CATEGORY,
			org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT,
			org.openforis.calc.persistence.jooq.tables.StratumTable.STRATUM,
			org.openforis.calc.persistence.jooq.tables.SurveyTable.SURVEY,
			org.openforis.calc.persistence.jooq.tables.TaxonTable.TAXON,
			org.openforis.calc.persistence.jooq.tables.TaxonomicChecklistTable.TAXONOMIC_CHECKLIST,
			org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME,
			org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE);
	}
}
