/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in calc
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * The table calc.aoi
	 */
	public static final org.openforis.calc.persistence.jooq.tables.AoiTable AOI = org.openforis.calc.persistence.jooq.tables.AoiTable.AOI;

	/**
	 * The table calc.aoi_hierarchy
	 */
	public static final org.openforis.calc.persistence.jooq.tables.AoiHierarchyTable AOI_HIERARCHY = org.openforis.calc.persistence.jooq.tables.AoiHierarchyTable.AOI_HIERARCHY;

	/**
	 * The table calc.category
	 */
	public static final org.openforis.calc.persistence.jooq.tables.CategoryTable CATEGORY = org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY;

	/**
	 * The table calc.cluster
	 */
	public static final org.openforis.calc.persistence.jooq.tables.ClusterTable CLUSTER = org.openforis.calc.persistence.jooq.tables.ClusterTable.CLUSTER;

	/**
	 * The table calc.ground_plot_view
	 */
	public static final org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable GROUND_PLOT_VIEW = org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW;

	/**
	 * The table calc.observation_unit
	 */
	public static final org.openforis.calc.persistence.jooq.tables.ObservationUnitTable OBSERVATION_UNIT = org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT;

	/**
	 * The table calc.operation
	 */
	public static final org.openforis.calc.persistence.jooq.tables.OperationTable OPERATION = org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION;

	/**
	 * The table calc.operation_parameter
	 */
	public static final org.openforis.calc.persistence.jooq.tables.OperationParameterTable OPERATION_PARAMETER = org.openforis.calc.persistence.jooq.tables.OperationParameterTable.OPERATION_PARAMETER;

	/**
	 * The table calc.plot
	 */
	public static final org.openforis.calc.persistence.jooq.tables.PlotTable PLOT = org.openforis.calc.persistence.jooq.tables.PlotTable.PLOT;

	/**
	 * The table calc.plot_category
	 */
	public static final org.openforis.calc.persistence.jooq.tables.PlotCategoryTable PLOT_CATEGORY = org.openforis.calc.persistence.jooq.tables.PlotCategoryTable.PLOT_CATEGORY;

	/**
	 * The table calc.plot_category_view
	 */
	public static final org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable PLOT_CATEGORY_VIEW = org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW;

	/**
	 * The table calc.plot_measurement
	 */
	public static final org.openforis.calc.persistence.jooq.tables.PlotMeasurementTable PLOT_MEASUREMENT = org.openforis.calc.persistence.jooq.tables.PlotMeasurementTable.PLOT_MEASUREMENT;

	/**
	 * The table calc.plot_measurement_view
	 */
	public static final org.openforis.calc.persistence.jooq.tables.PlotMeasurementViewTable PLOT_MEASUREMENT_VIEW = org.openforis.calc.persistence.jooq.tables.PlotMeasurementViewTable.PLOT_MEASUREMENT_VIEW;

	/**
	 * The table calc.plot_survey
	 */
	public static final org.openforis.calc.persistence.jooq.tables.PlotSurveyTable PLOT_SURVEY = org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY;

	/**
	 * The table calc.plot_survey_view
	 */
	public static final org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable PLOT_SURVEY_VIEW = org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW;

	/**
	 * The table calc.plot_view
	 */
	public static final org.openforis.calc.persistence.jooq.tables.PlotViewTable PLOT_VIEW = org.openforis.calc.persistence.jooq.tables.PlotViewTable.PLOT_VIEW;

	/**
	 * The table calc.process
	 */
	public static final org.openforis.calc.persistence.jooq.tables.ProcessTable PROCESS = org.openforis.calc.persistence.jooq.tables.ProcessTable.PROCESS;

	/**
	 * The table calc.processing_chain
	 */
	public static final org.openforis.calc.persistence.jooq.tables.ProcessingChainTable PROCESSING_CHAIN = org.openforis.calc.persistence.jooq.tables.ProcessingChainTable.PROCESSING_CHAIN;

	/**
	 * The table calc.specimen
	 */
	public static final org.openforis.calc.persistence.jooq.tables.SpecimenTable SPECIMEN = org.openforis.calc.persistence.jooq.tables.SpecimenTable.SPECIMEN;

	/**
	 * The table calc.specimen_category
	 */
	public static final org.openforis.calc.persistence.jooq.tables.SpecimenCategoryTable SPECIMEN_CATEGORY = org.openforis.calc.persistence.jooq.tables.SpecimenCategoryTable.SPECIMEN_CATEGORY;

	/**
	 * The table calc.specimen_measurement
	 */
	public static final org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable SPECIMEN_MEASUREMENT = org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT;

	/**
	 * The table calc.stratum
	 */
	public static final org.openforis.calc.persistence.jooq.tables.StratumTable STRATUM = org.openforis.calc.persistence.jooq.tables.StratumTable.STRATUM;

	/**
	 * The table calc.survey
	 */
	public static final org.openforis.calc.persistence.jooq.tables.SurveyTable SURVEY = org.openforis.calc.persistence.jooq.tables.SurveyTable.SURVEY;

	/**
	 * The table calc.taxon
	 */
	public static final org.openforis.calc.persistence.jooq.tables.TaxonTable TAXON = org.openforis.calc.persistence.jooq.tables.TaxonTable.TAXON;

	/**
	 * The table calc.taxonomic_checklist
	 */
	public static final org.openforis.calc.persistence.jooq.tables.TaxonomicChecklistTable TAXONOMIC_CHECKLIST = org.openforis.calc.persistence.jooq.tables.TaxonomicChecklistTable.TAXONOMIC_CHECKLIST;

	/**
	 * The table calc.taxon_vernacular_name
	 */
	public static final org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable TAXON_VERNACULAR_NAME = org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME;

	/**
	 * The table calc.variable
	 */
	public static final org.openforis.calc.persistence.jooq.tables.VariableTable VARIABLE = org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE;

	/**
	 * No instances
	 */
	private Tables() {}
}
