package org.openforis.calc.model;

// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plot generated by hbm2java
 */
@Entity
@Table(name = "plot")
public class Plot implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Cluster cluster;
	private String code;
	private String label;
	private String location;
	private int phase;
	private Set<PlotObs> plotObses = new HashSet<PlotObs>(0);

	public Plot() {
	}

	public Plot(int id, Cluster cluster, String code, int phase) {
		this.id = id;
		this.cluster = cluster;
		this.code = code;
		this.phase = phase;
	}

	public Plot(int id, Cluster cluster, String code, String label, String location, int phase, Set<PlotObs> plotObses) {
		this.id = id;
		this.cluster = cluster;
		this.code = code;
		this.label = label;
		this.location = location;
		this.phase = phase;
		this.plotObses = plotObses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cluster_id", nullable = false)
	public Cluster getCluster() {
		return this.cluster;
	}

	public void setCluster(Cluster cluster) {
		this.cluster = cluster;
	}

	@Column(name = "code", nullable = false, length = 25)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "location")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "phase", nullable = false)
	public int getPhase() {
		return this.phase;
	}

	public void setPhase(int phase) {
		this.phase = phase;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plot")
	public Set<PlotObs> getPlotObses() {
		return this.plotObses;
	}

	public void setPlotObses(Set<PlotObs> plotObses) {
		this.plotObses = plotObses;
	}

}
