package org.openforis.calc.model;

// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdminUnitPlotCountId generated by hbm2java
 */
@Embeddable
public class AdminUnitPlotCountId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer adminUnitId;
	private Long count;

	public AdminUnitPlotCountId() {
	}

	public AdminUnitPlotCountId(Integer adminUnitId, Long count) {
		this.adminUnitId = adminUnitId;
		this.count = count;
	}

	@Column(name = "admin_unit_id")
	public Integer getAdminUnitId() {
		return this.adminUnitId;
	}

	public void setAdminUnitId(Integer adminUnitId) {
		this.adminUnitId = adminUnitId;
	}

	@Column(name = "count")
	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	@Override
	public boolean equals(Object other) {
		if ( this == other ) {
			return true;
		}
		if ( other == null ) {
			return false;
		}
		if ( !(other instanceof AdminUnitPlotCountId) ) {
			return false;
		}
		final AdminUnitPlotCountId castOther = (AdminUnitPlotCountId) other;

		return (this.getAdminUnitId() == castOther.getAdminUnitId() || this.getAdminUnitId() != null && castOther.getAdminUnitId() != null && this.getAdminUnitId().equals(castOther.getAdminUnitId()))
				&& (this.getCount() == castOther.getCount() || this.getCount() != null && castOther.getCount() != null && this.getCount().equals(castOther.getCount()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAdminUnitId() == null ? 0 : this.getAdminUnitId().hashCode());
		result = 37 * result + (getCount() == null ? 0 : this.getCount().hashCode());
		return result;
	}

}
