package org.openforis.calc.model;
// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AdminUnitPlotCount generated by hbm2java
 */
@Entity
@Table(name="admin_unit_plot_count"
)
public class AdminUnitPlotCount  implements java.io.Serializable {


     private AdminUnitPlotCountId id;

    public AdminUnitPlotCount() {
    }

    public AdminUnitPlotCount(AdminUnitPlotCountId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="adminUnitId", column=@Column(name="admin_unit_id") ), 
        @AttributeOverride(name="count", column=@Column(name="count") ) } )
    public AdminUnitPlotCountId getId() {
        return this.id;
    }
    
    public void setId(AdminUnitPlotCountId id) {
        this.id = id;
    }




}


