package org.openforis.calc.model;
// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdminUnit generated by hbm2java
 */
@Entity
@Table(name="admin_unit"
)
public class AdminUnit  implements java.io.Serializable {


     private int id;
     private String fullCode;
     private String level1Name;
     private String level2Name;
     private BigDecimal area;
     private String level1Code;
     private String level2Code;
     private Set<Cluster> clusters = new HashSet<Cluster>(0);

    public AdminUnit() {
    }

	
    public AdminUnit(int id) {
        this.id = id;
    }
    public AdminUnit(int id, String fullCode, String level1Name, String level2Name, BigDecimal area, String level1Code, String level2Code, Set<Cluster> clusters) {
       this.id = id;
       this.fullCode = fullCode;
       this.level1Name = level1Name;
       this.level2Name = level2Name;
       this.area = area;
       this.level1Code = level1Code;
       this.level2Code = level2Code;
       this.clusters = clusters;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="full_code", length=25)
    public String getFullCode() {
        return this.fullCode;
    }
    
    public void setFullCode(String fullCode) {
        this.fullCode = fullCode;
    }

    
    @Column(name="level1_name")
    public String getLevel1Name() {
        return this.level1Name;
    }
    
    public void setLevel1Name(String level1Name) {
        this.level1Name = level1Name;
    }

    
    @Column(name="level2_name")
    public String getLevel2Name() {
        return this.level2Name;
    }
    
    public void setLevel2Name(String level2Name) {
        this.level2Name = level2Name;
    }

    
    @Column(name="area", precision=15, scale=5)
    public BigDecimal getArea() {
        return this.area;
    }
    
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    
    @Column(name="level1_code", length=25)
    public String getLevel1Code() {
        return this.level1Code;
    }
    
    public void setLevel1Code(String level1Code) {
        this.level1Code = level1Code;
    }

    
    @Column(name="level2_code", length=25)
    public String getLevel2Code() {
        return this.level2Code;
    }
    
    public void setLevel2Code(String level2Code) {
        this.level2Code = level2Code;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="adminUnit")
    public Set<Cluster> getClusters() {
        return this.clusters;
    }
    
    public void setClusters(Set<Cluster> clusters) {
        this.clusters = clusters;
    }




}


