package org.openforis.calc.model;

// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cluster generated by hbm2java
 */
@Entity
@Table(name = "cluster")
public class Cluster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Stratum stratum;
	private AdminUnit adminUnit;
	private String code;
	private String label;
	private Integer phase;
	private Set<Plot> plots = new HashSet<Plot>(0);

	public Cluster() {
	}

	public Cluster(int id, String code) {
		this.id = id;
		this.code = code;
	}

	public Cluster(int id, Stratum stratum, AdminUnit adminUnit, String code, String label, Integer phase, Set<Plot> plots) {
		this.id = id;
		this.stratum = stratum;
		this.adminUnit = adminUnit;
		this.code = code;
		this.label = label;
		this.phase = phase;
		this.plots = plots;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stratum_id")
	public Stratum getStratum() {
		return this.stratum;
	}

	public void setStratum(Stratum stratum) {
		this.stratum = stratum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "admin_unit_id")
	public AdminUnit getAdminUnit() {
		return this.adminUnit;
	}

	public void setAdminUnit(AdminUnit adminUnit) {
		this.adminUnit = adminUnit;
	}

	@Column(name = "code", nullable = false, length = 25)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "phase")
	public Integer getPhase() {
		return this.phase;
	}

	public void setPhase(Integer phase) {
		this.phase = phase;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cluster")
	public Set<Plot> getPlots() {
		return this.plots;
	}

	public void setPlots(Set<Plot> plots) {
		this.plots = plots;
	}

}
