package org.openforis.calc.model;
// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PlotObs generated by hbm2java
 */
@Entity
@Table(name="plot_obs"
)
public class PlotObs  implements java.io.Serializable {


     private int id;
     private PlotClass5 plotClass5;
     private PlotClass4 plotClass4;
     private PlotClass2 plotClass2;
     private Plot plot;
     private PlotClass3 plotClass3;
     private PlotClass1 plotClass1;
     private String section;
     private BigDecimal share;
     private BigDecimal estArea;
     private Integer accessibilityId;
     private Integer adminUnitId;
     private Integer center;
     private BigDecimal slope;
     private Integer slopeCorrectionApplied;
     private Double inclusionProbability;
     private String location;
     private Double hteArea;
     private Set<TreeObs> treeObses = new HashSet<TreeObs>(0);

    public PlotObs() {
    }

	
    public PlotObs(int id, Plot plot) {
        this.id = id;
        this.plot = plot;
    }
    public PlotObs(int id, PlotClass5 plotClass5, PlotClass4 plotClass4, PlotClass2 plotClass2, Plot plot, PlotClass3 plotClass3, PlotClass1 plotClass1, String section, BigDecimal share, BigDecimal estArea, Integer accessibilityId, Integer adminUnitId, Integer center, BigDecimal slope, Integer slopeCorrectionApplied, Double inclusionProbability, String location, Double hteArea, Set<TreeObs> treeObses) {
       this.id = id;
       this.plotClass5 = plotClass5;
       this.plotClass4 = plotClass4;
       this.plotClass2 = plotClass2;
       this.plot = plot;
       this.plotClass3 = plotClass3;
       this.plotClass1 = plotClass1;
       this.section = section;
       this.share = share;
       this.estArea = estArea;
       this.accessibilityId = accessibilityId;
       this.adminUnitId = adminUnitId;
       this.center = center;
       this.slope = slope;
       this.slopeCorrectionApplied = slopeCorrectionApplied;
       this.inclusionProbability = inclusionProbability;
       this.location = location;
       this.hteArea = hteArea;
       this.treeObses = treeObses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class5_id")
    public PlotClass5 getPlotClass5() {
        return this.plotClass5;
    }
    
    public void setPlotClass5(PlotClass5 plotClass5) {
        this.plotClass5 = plotClass5;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class4_id")
    public PlotClass4 getPlotClass4() {
        return this.plotClass4;
    }
    
    public void setPlotClass4(PlotClass4 plotClass4) {
        this.plotClass4 = plotClass4;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class2_id")
    public PlotClass2 getPlotClass2() {
        return this.plotClass2;
    }
    
    public void setPlotClass2(PlotClass2 plotClass2) {
        this.plotClass2 = plotClass2;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="plot_id", nullable=false)
    public Plot getPlot() {
        return this.plot;
    }
    
    public void setPlot(Plot plot) {
        this.plot = plot;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class3_id")
    public PlotClass3 getPlotClass3() {
        return this.plotClass3;
    }
    
    public void setPlotClass3(PlotClass3 plotClass3) {
        this.plotClass3 = plotClass3;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class1_id")
    public PlotClass1 getPlotClass1() {
        return this.plotClass1;
    }
    
    public void setPlotClass1(PlotClass1 plotClass1) {
        this.plotClass1 = plotClass1;
    }

    
    @Column(name="section", length=25)
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }

    
    @Column(name="share", precision=15, scale=5)
    public BigDecimal getShare() {
        return this.share;
    }
    
    public void setShare(BigDecimal share) {
        this.share = share;
    }

    
    @Column(name="est_area", precision=15, scale=5)
    public BigDecimal getEstArea() {
        return this.estArea;
    }
    
    public void setEstArea(BigDecimal estArea) {
        this.estArea = estArea;
    }

    
    @Column(name="accessibility_id")
    public Integer getAccessibilityId() {
        return this.accessibilityId;
    }
    
    public void setAccessibilityId(Integer accessibilityId) {
        this.accessibilityId = accessibilityId;
    }

    
    @Column(name="admin_unit_id")
    public Integer getAdminUnitId() {
        return this.adminUnitId;
    }
    
    public void setAdminUnitId(Integer adminUnitId) {
        this.adminUnitId = adminUnitId;
    }

    
    @Column(name="center")
    public Integer getCenter() {
        return this.center;
    }
    
    public void setCenter(Integer center) {
        this.center = center;
    }

    
    @Column(name="slope", precision=15, scale=5)
    public BigDecimal getSlope() {
        return this.slope;
    }
    
    public void setSlope(BigDecimal slope) {
        this.slope = slope;
    }

    
    @Column(name="slope_correction_applied")
    public Integer getSlopeCorrectionApplied() {
        return this.slopeCorrectionApplied;
    }
    
    public void setSlopeCorrectionApplied(Integer slopeCorrectionApplied) {
        this.slopeCorrectionApplied = slopeCorrectionApplied;
    }

    
    @Column(name="inclusion_probability", precision=17, scale=17)
    public Double getInclusionProbability() {
        return this.inclusionProbability;
    }
    
    public void setInclusionProbability(Double inclusionProbability) {
        this.inclusionProbability = inclusionProbability;
    }

    
    @Column(name="location", length=25)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="hte_area", precision=17, scale=17)
    public Double getHteArea() {
        return this.hteArea;
    }
    
    public void setHteArea(Double hteArea) {
        this.hteArea = hteArea;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="plotObs")
    public Set<TreeObs> getTreeObses() {
        return this.treeObses;
    }
    
    public void setTreeObses(Set<TreeObs> treeObses) {
        this.treeObses = treeObses;
    }




}


