package org.openforis.calc.model;

// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PlotObsView generated by hbm2java
 */
@Entity
@Table(name = "plot_obs_view")
public class PlotObsView implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PlotObsViewId id;

	public PlotObsView() {
	}

	public PlotObsView(PlotObsViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")), @AttributeOverride(name = "plotId", column = @Column(name = "plot_id")),
			@AttributeOverride(name = "section", column = @Column(name = "section", length = 25)), @AttributeOverride(name = "share", column = @Column(name = "share", precision = 15, scale = 5)),
			@AttributeOverride(name = "estArea", column = @Column(name = "est_area", precision = 15, scale = 5)),
			@AttributeOverride(name = "accessibilityId", column = @Column(name = "accessibility_id")), @AttributeOverride(name = "adminUnitId", column = @Column(name = "admin_unit_id")),
			@AttributeOverride(name = "class1Id", column = @Column(name = "class1_id")), @AttributeOverride(name = "class2Id", column = @Column(name = "class2_id")),
			@AttributeOverride(name = "class3Id", column = @Column(name = "class3_id")), @AttributeOverride(name = "class4Id", column = @Column(name = "class4_id")),
			@AttributeOverride(name = "class5Id", column = @Column(name = "class5_id")), @AttributeOverride(name = "center", column = @Column(name = "center")),
			@AttributeOverride(name = "slope", column = @Column(name = "slope", precision = 15, scale = 5)),
			@AttributeOverride(name = "slopeCorrectionApplied", column = @Column(name = "slope_correction_applied")),
			@AttributeOverride(name = "inclusionProbability", column = @Column(name = "inclusion_probability", precision = 17, scale = 17)),
			@AttributeOverride(name = "location", column = @Column(name = "location", length = 25)),
			@AttributeOverride(name = "hteArea", column = @Column(name = "hte_area", precision = 17, scale = 17)), @AttributeOverride(name = "clusterId", column = @Column(name = "cluster_id")),
			@AttributeOverride(name = "stratumId", column = @Column(name = "stratum_id")), @AttributeOverride(name = "TAdminUnitId", column = @Column(name = "t_admin_unit_id")) })
	public PlotObsViewId getId() {
		return this.id;
	}

	public void setId(PlotObsViewId id) {
		this.id = id;
	}

}
