package org.openforis.calc.model;

// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlotObsViewId generated by hbm2java
 */
@Embeddable
public class PlotObsViewId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer plotId;
	private String section;
	private BigDecimal share;
	private BigDecimal estArea;
	private Integer accessibilityId;
	private Integer adminUnitId;
	private Integer class1Id;
	private Integer class2Id;
	private Integer class3Id;
	private Integer class4Id;
	private Integer class5Id;
	private Integer center;
	private BigDecimal slope;
	private Integer slopeCorrectionApplied;
	private Double inclusionProbability;
	private String location;
	private Double hteArea;
	private Integer clusterId;
	private Integer stratumId;
	private Integer TAdminUnitId;

	public PlotObsViewId() {
	}

	public PlotObsViewId(Integer id, Integer plotId, String section, BigDecimal share, BigDecimal estArea, Integer accessibilityId, Integer adminUnitId, Integer class1Id, Integer class2Id,
			Integer class3Id, Integer class4Id, Integer class5Id, Integer center, BigDecimal slope, Integer slopeCorrectionApplied, Double inclusionProbability, String location, Double hteArea,
			Integer clusterId, Integer stratumId, Integer TAdminUnitId) {
		this.id = id;
		this.plotId = plotId;
		this.section = section;
		this.share = share;
		this.estArea = estArea;
		this.accessibilityId = accessibilityId;
		this.adminUnitId = adminUnitId;
		this.class1Id = class1Id;
		this.class2Id = class2Id;
		this.class3Id = class3Id;
		this.class4Id = class4Id;
		this.class5Id = class5Id;
		this.center = center;
		this.slope = slope;
		this.slopeCorrectionApplied = slopeCorrectionApplied;
		this.inclusionProbability = inclusionProbability;
		this.location = location;
		this.hteArea = hteArea;
		this.clusterId = clusterId;
		this.stratumId = stratumId;
		this.TAdminUnitId = TAdminUnitId;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "plot_id")
	public Integer getPlotId() {
		return this.plotId;
	}

	public void setPlotId(Integer plotId) {
		this.plotId = plotId;
	}

	@Column(name = "section", length = 25)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	@Column(name = "share", precision = 15, scale = 5)
	public BigDecimal getShare() {
		return this.share;
	}

	public void setShare(BigDecimal share) {
		this.share = share;
	}

	@Column(name = "est_area", precision = 15, scale = 5)
	public BigDecimal getEstArea() {
		return this.estArea;
	}

	public void setEstArea(BigDecimal estArea) {
		this.estArea = estArea;
	}

	@Column(name = "accessibility_id")
	public Integer getAccessibilityId() {
		return this.accessibilityId;
	}

	public void setAccessibilityId(Integer accessibilityId) {
		this.accessibilityId = accessibilityId;
	}

	@Column(name = "admin_unit_id")
	public Integer getAdminUnitId() {
		return this.adminUnitId;
	}

	public void setAdminUnitId(Integer adminUnitId) {
		this.adminUnitId = adminUnitId;
	}

	@Column(name = "class1_id")
	public Integer getClass1Id() {
		return this.class1Id;
	}

	public void setClass1Id(Integer class1Id) {
		this.class1Id = class1Id;
	}

	@Column(name = "class2_id")
	public Integer getClass2Id() {
		return this.class2Id;
	}

	public void setClass2Id(Integer class2Id) {
		this.class2Id = class2Id;
	}

	@Column(name = "class3_id")
	public Integer getClass3Id() {
		return this.class3Id;
	}

	public void setClass3Id(Integer class3Id) {
		this.class3Id = class3Id;
	}

	@Column(name = "class4_id")
	public Integer getClass4Id() {
		return this.class4Id;
	}

	public void setClass4Id(Integer class4Id) {
		this.class4Id = class4Id;
	}

	@Column(name = "class5_id")
	public Integer getClass5Id() {
		return this.class5Id;
	}

	public void setClass5Id(Integer class5Id) {
		this.class5Id = class5Id;
	}

	@Column(name = "center")
	public Integer getCenter() {
		return this.center;
	}

	public void setCenter(Integer center) {
		this.center = center;
	}

	@Column(name = "slope", precision = 15, scale = 5)
	public BigDecimal getSlope() {
		return this.slope;
	}

	public void setSlope(BigDecimal slope) {
		this.slope = slope;
	}

	@Column(name = "slope_correction_applied")
	public Integer getSlopeCorrectionApplied() {
		return this.slopeCorrectionApplied;
	}

	public void setSlopeCorrectionApplied(Integer slopeCorrectionApplied) {
		this.slopeCorrectionApplied = slopeCorrectionApplied;
	}

	@Column(name = "inclusion_probability", precision = 17, scale = 17)
	public Double getInclusionProbability() {
		return this.inclusionProbability;
	}

	public void setInclusionProbability(Double inclusionProbability) {
		this.inclusionProbability = inclusionProbability;
	}

	@Column(name = "location", length = 25)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "hte_area", precision = 17, scale = 17)
	public Double getHteArea() {
		return this.hteArea;
	}

	public void setHteArea(Double hteArea) {
		this.hteArea = hteArea;
	}

	@Column(name = "cluster_id")
	public Integer getClusterId() {
		return this.clusterId;
	}

	public void setClusterId(Integer clusterId) {
		this.clusterId = clusterId;
	}

	@Column(name = "stratum_id")
	public Integer getStratumId() {
		return this.stratumId;
	}

	public void setStratumId(Integer stratumId) {
		this.stratumId = stratumId;
	}

	@Column(name = "t_admin_unit_id")
	public Integer getTAdminUnitId() {
		return this.TAdminUnitId;
	}

	public void setTAdminUnitId(Integer TAdminUnitId) {
		this.TAdminUnitId = TAdminUnitId;
	}

	@Override
	public boolean equals(Object other) {
		if ( this == other ) {
			return true;
		}
		if ( other == null ) {
			return false;
		}
		if ( !(other instanceof PlotObsViewId) ) {
			return false;
		}
		final PlotObsViewId castOther = (PlotObsViewId) other;

		return (this.getId() == castOther.getId() || this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId()))
				&& (this.getPlotId() == castOther.getPlotId() || this.getPlotId() != null && castOther.getPlotId() != null && this.getPlotId().equals(castOther.getPlotId()))
				&& (this.getSection() == castOther.getSection() || this.getSection() != null && castOther.getSection() != null && this.getSection().equals(castOther.getSection()))
				&& (this.getShare() == castOther.getShare() || this.getShare() != null && castOther.getShare() != null && this.getShare().equals(castOther.getShare()))
				&& (this.getEstArea() == castOther.getEstArea() || this.getEstArea() != null && castOther.getEstArea() != null && this.getEstArea().equals(castOther.getEstArea()))
				&& (this.getAccessibilityId() == castOther.getAccessibilityId() || this.getAccessibilityId() != null && castOther.getAccessibilityId() != null
						&& this.getAccessibilityId().equals(castOther.getAccessibilityId()))
				&& (this.getAdminUnitId() == castOther.getAdminUnitId() || this.getAdminUnitId() != null && castOther.getAdminUnitId() != null
						&& this.getAdminUnitId().equals(castOther.getAdminUnitId()))
				&& (this.getClass1Id() == castOther.getClass1Id() || this.getClass1Id() != null && castOther.getClass1Id() != null && this.getClass1Id().equals(castOther.getClass1Id()))
				&& (this.getClass2Id() == castOther.getClass2Id() || this.getClass2Id() != null && castOther.getClass2Id() != null && this.getClass2Id().equals(castOther.getClass2Id()))
				&& (this.getClass3Id() == castOther.getClass3Id() || this.getClass3Id() != null && castOther.getClass3Id() != null && this.getClass3Id().equals(castOther.getClass3Id()))
				&& (this.getClass4Id() == castOther.getClass4Id() || this.getClass4Id() != null && castOther.getClass4Id() != null && this.getClass4Id().equals(castOther.getClass4Id()))
				&& (this.getClass5Id() == castOther.getClass5Id() || this.getClass5Id() != null && castOther.getClass5Id() != null && this.getClass5Id().equals(castOther.getClass5Id()))
				&& (this.getCenter() == castOther.getCenter() || this.getCenter() != null && castOther.getCenter() != null && this.getCenter().equals(castOther.getCenter()))
				&& (this.getSlope() == castOther.getSlope() || this.getSlope() != null && castOther.getSlope() != null && this.getSlope().equals(castOther.getSlope()))
				&& (this.getSlopeCorrectionApplied() == castOther.getSlopeCorrectionApplied() || this.getSlopeCorrectionApplied() != null && castOther.getSlopeCorrectionApplied() != null
						&& this.getSlopeCorrectionApplied().equals(castOther.getSlopeCorrectionApplied()))
				&& (this.getInclusionProbability() == castOther.getInclusionProbability() || this.getInclusionProbability() != null && castOther.getInclusionProbability() != null
						&& this.getInclusionProbability().equals(castOther.getInclusionProbability()))
				&& (this.getLocation() == castOther.getLocation() || this.getLocation() != null && castOther.getLocation() != null && this.getLocation().equals(castOther.getLocation()))
				&& (this.getHteArea() == castOther.getHteArea() || this.getHteArea() != null && castOther.getHteArea() != null && this.getHteArea().equals(castOther.getHteArea()))
				&& (this.getClusterId() == castOther.getClusterId() || this.getClusterId() != null && castOther.getClusterId() != null && this.getClusterId().equals(castOther.getClusterId()))
				&& (this.getStratumId() == castOther.getStratumId() || this.getStratumId() != null && castOther.getStratumId() != null && this.getStratumId().equals(castOther.getStratumId()))
				&& (this.getTAdminUnitId() == castOther.getTAdminUnitId() || this.getTAdminUnitId() != null && castOther.getTAdminUnitId() != null
						&& this.getTAdminUnitId().equals(castOther.getTAdminUnitId()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getPlotId() == null ? 0 : this.getPlotId().hashCode());
		result = 37 * result + (getSection() == null ? 0 : this.getSection().hashCode());
		result = 37 * result + (getShare() == null ? 0 : this.getShare().hashCode());
		result = 37 * result + (getEstArea() == null ? 0 : this.getEstArea().hashCode());
		result = 37 * result + (getAccessibilityId() == null ? 0 : this.getAccessibilityId().hashCode());
		result = 37 * result + (getAdminUnitId() == null ? 0 : this.getAdminUnitId().hashCode());
		result = 37 * result + (getClass1Id() == null ? 0 : this.getClass1Id().hashCode());
		result = 37 * result + (getClass2Id() == null ? 0 : this.getClass2Id().hashCode());
		result = 37 * result + (getClass3Id() == null ? 0 : this.getClass3Id().hashCode());
		result = 37 * result + (getClass4Id() == null ? 0 : this.getClass4Id().hashCode());
		result = 37 * result + (getClass5Id() == null ? 0 : this.getClass5Id().hashCode());
		result = 37 * result + (getCenter() == null ? 0 : this.getCenter().hashCode());
		result = 37 * result + (getSlope() == null ? 0 : this.getSlope().hashCode());
		result = 37 * result + (getSlopeCorrectionApplied() == null ? 0 : this.getSlopeCorrectionApplied().hashCode());
		result = 37 * result + (getInclusionProbability() == null ? 0 : this.getInclusionProbability().hashCode());
		result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
		result = 37 * result + (getHteArea() == null ? 0 : this.getHteArea().hashCode());
		result = 37 * result + (getClusterId() == null ? 0 : this.getClusterId().hashCode());
		result = 37 * result + (getStratumId() == null ? 0 : this.getStratumId().hashCode());
		result = 37 * result + (getTAdminUnitId() == null ? 0 : this.getTAdminUnitId().hashCode());
		return result;
	}

}
