package org.openforis.calc.model;

// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StratumPlotDensity generated by hbm2java
 */
@Entity
@Table(name = "stratum_plot_density")
public class StratumPlotDensity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private StratumPlotDensityId id;

	public StratumPlotDensity() {
	}

	public StratumPlotDensity(StratumPlotDensityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "stratumId", column = @Column(name = "stratum_id")),
			@AttributeOverride(name = "plotDensity", column = @Column(name = "plot_density", precision = 17, scale = 17)) })
	public StratumPlotDensityId getId() {
		return this.id;
	}

	public void setId(StratumPlotDensityId id) {
		this.id = id;
	}

}
