package org.openforis.calc.model;

// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StratumPlotCountId generated by hbm2java
 */
@Embeddable
public class StratumPlotCountId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer stratumId;
	private Long count;

	public StratumPlotCountId() {
	}

	public StratumPlotCountId(Integer stratumId, Long count) {
		this.stratumId = stratumId;
		this.count = count;
	}

	@Column(name = "stratum_id")
	public Integer getStratumId() {
		return this.stratumId;
	}

	public void setStratumId(Integer stratumId) {
		this.stratumId = stratumId;
	}

	@Column(name = "count")
	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	@Override
	public boolean equals(Object other) {
		if ( this == other ) {
			return true;
		}
		if ( other == null ) {
			return false;
		}
		if ( !(other instanceof StratumPlotCountId) ) {
			return false;
		}
		final StratumPlotCountId castOther = (StratumPlotCountId) other;

		return (this.getStratumId() == castOther.getStratumId() || this.getStratumId() != null && castOther.getStratumId() != null && this.getStratumId().equals(castOther.getStratumId()))
				&& (this.getCount() == castOther.getCount() || this.getCount() != null && castOther.getCount() != null && this.getCount().equals(castOther.getCount()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStratumId() == null ? 0 : this.getStratumId().hashCode());
		result = 37 * result + (getCount() == null ? 0 : this.getCount().hashCode());
		return result;
	}

}
