package org.openforis.calc.model;
// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stratum generated by hbm2java
 */
@Entity
@Table(name="stratum"
)
public class Stratum  implements java.io.Serializable {


     private int id;
     private String code;
     private String label;
     private BigDecimal estArea;
     private Set<Cluster> clusters = new HashSet<Cluster>(0);

    public Stratum() {
    }

	
    public Stratum(int id) {
        this.id = id;
    }
    public Stratum(int id, String code, String label, BigDecimal estArea, Set<Cluster> clusters) {
       this.id = id;
       this.code = code;
       this.label = label;
       this.estArea = estArea;
       this.clusters = clusters;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="code", length=25)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="label")
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    
    @Column(name="est_area", precision=15, scale=5)
    public BigDecimal getEstArea() {
        return this.estArea;
    }
    
    public void setEstArea(BigDecimal estArea) {
        this.estArea = estArea;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stratum")
    public Set<Cluster> getClusters() {
        return this.clusters;
    }
    
    public void setClusters(Set<Cluster> clusters) {
        this.clusters = clusters;
    }




}


