package org.openforis.calc.model;
// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StratumPlotCount generated by hbm2java
 */
@Entity
@Table(name="stratum_plot_count"
)
public class StratumPlotCount  implements java.io.Serializable {


     private StratumPlotCountId id;

    public StratumPlotCount() {
    }

    public StratumPlotCount(StratumPlotCountId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="stratumId", column=@Column(name="stratum_id") ), 
        @AttributeOverride(name="count", column=@Column(name="count") ) } )
    public StratumPlotCountId getId() {
        return this.id;
    }
    
    public void setId(StratumPlotCountId id) {
        this.id = id;
    }




}


