package org.openforis.calc.model;
// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StratumArea generated by hbm2java
 */
@Entity
@Table(name="stratum_area"
)
public class StratumArea  implements java.io.Serializable {


     private StratumAreaId id;

    public StratumArea() {
    }

    public StratumArea(StratumAreaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="stratumId", column=@Column(name="stratum_id") ), 
        @AttributeOverride(name="area", column=@Column(name="area", precision=17, scale=17) ) } )
    public StratumAreaId getId() {
        return this.id;
    }
    
    public void setId(StratumAreaId id) {
        this.id = id;
    }




}


