package org.openforis.calc.model;
// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SubstratumWeight generated by hbm2java
 */
@Entity
@Table(name="substratum_weight"
)
public class SubstratumWeight  implements java.io.Serializable {


     private SubstratumWeightId id;

    public SubstratumWeight() {
    }

    public SubstratumWeight(SubstratumWeightId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="adminUnitId", column=@Column(name="admin_unit_id") ), 
        @AttributeOverride(name="stratumId", column=@Column(name="stratum_id") ), 
        @AttributeOverride(name="substratumPlotCount", column=@Column(name="substratum_plot_count") ), 
        @AttributeOverride(name="weight", column=@Column(name="weight", precision=17, scale=17) ) } )
    public SubstratumWeightId getId() {
        return this.id;
    }
    
    public void setId(SubstratumWeightId id) {
        this.id = id;
    }




}


