package org.openforis.calc.model;

// Generated Aug 8, 2012 5:42:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TreeObs generated by hbm2java
 */
@Entity
@Table(name = "tree_obs")
public class TreeObs implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int id;
	private TreeHealth treeHealth;
	private PlotObs plotObs;
	private Integer taxonId;
	private Integer originId;
	private BigDecimal dbh;
	private BigDecimal dbhHeight;
	private BigDecimal topHeight;
	private BigDecimal boleHeight;
	private BigDecimal stumpDiameter;
	private BigDecimal stumpHeight;
	private BigDecimal inclusionArea;
	private Double inclusionProbability;
	private BigDecimal estTopHeight;
	private BigDecimal estBasalArea;
	private BigDecimal estStemVolume;
	private BigDecimal estBoleVolume;
	private BigDecimal estTopVolume;
	private BigDecimal estVolume;
	private BigDecimal estStemBiomass;
	private BigDecimal estAgBiomass;
	private BigDecimal estBgBiomass;
	private BigDecimal estBiomass;
	private BigDecimal estStemCarbon;
	private BigDecimal estAgCarbon;
	private BigDecimal estBgCarbon;
	private BigDecimal estCarbon;

	public TreeObs() {
	}

	public TreeObs(int id, PlotObs plotObs) {
		this.id = id;
		this.plotObs = plotObs;
	}

	public TreeObs(int id, TreeHealth treeHealth, PlotObs plotObs, Integer taxonId, Integer originId, BigDecimal dbh, BigDecimal dbhHeight, BigDecimal topHeight, BigDecimal boleHeight,
			BigDecimal stumpDiameter, BigDecimal stumpHeight, BigDecimal inclusionArea, Double inclusionProbability, BigDecimal estTopHeight, BigDecimal estBasalArea, BigDecimal estStemVolume,
			BigDecimal estBoleVolume, BigDecimal estTopVolume, BigDecimal estVolume, BigDecimal estStemBiomass, BigDecimal estAgBiomass, BigDecimal estBgBiomass, BigDecimal estBiomass,
			BigDecimal estStemCarbon, BigDecimal estAgCarbon, BigDecimal estBgCarbon, BigDecimal estCarbon) {
		this.id = id;
		this.treeHealth = treeHealth;
		this.plotObs = plotObs;
		this.taxonId = taxonId;
		this.originId = originId;
		this.dbh = dbh;
		this.dbhHeight = dbhHeight;
		this.topHeight = topHeight;
		this.boleHeight = boleHeight;
		this.stumpDiameter = stumpDiameter;
		this.stumpHeight = stumpHeight;
		this.inclusionArea = inclusionArea;
		this.inclusionProbability = inclusionProbability;
		this.estTopHeight = estTopHeight;
		this.estBasalArea = estBasalArea;
		this.estStemVolume = estStemVolume;
		this.estBoleVolume = estBoleVolume;
		this.estTopVolume = estTopVolume;
		this.estVolume = estVolume;
		this.estStemBiomass = estStemBiomass;
		this.estAgBiomass = estAgBiomass;
		this.estBgBiomass = estBgBiomass;
		this.estBiomass = estBiomass;
		this.estStemCarbon = estStemCarbon;
		this.estAgCarbon = estAgCarbon;
		this.estBgCarbon = estBgCarbon;
		this.estCarbon = estCarbon;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "health_id")
	public TreeHealth getTreeHealth() {
		return this.treeHealth;
	}

	public void setTreeHealth(TreeHealth treeHealth) {
		this.treeHealth = treeHealth;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plot_obs_id", nullable = false)
	public PlotObs getPlotObs() {
		return this.plotObs;
	}

	public void setPlotObs(PlotObs plotObs) {
		this.plotObs = plotObs;
	}

	@Column(name = "taxon_id")
	public Integer getTaxonId() {
		return this.taxonId;
	}

	public void setTaxonId(Integer taxonId) {
		this.taxonId = taxonId;
	}

	@Column(name = "origin_id")
	public Integer getOriginId() {
		return this.originId;
	}

	public void setOriginId(Integer originId) {
		this.originId = originId;
	}

	@Column(name = "dbh", precision = 15, scale = 5)
	public BigDecimal getDbh() {
		return this.dbh;
	}

	public void setDbh(BigDecimal dbh) {
		this.dbh = dbh;
	}

	@Column(name = "dbh_height", precision = 15, scale = 5)
	public BigDecimal getDbhHeight() {
		return this.dbhHeight;
	}

	public void setDbhHeight(BigDecimal dbhHeight) {
		this.dbhHeight = dbhHeight;
	}

	@Column(name = "top_height", precision = 15, scale = 5)
	public BigDecimal getTopHeight() {
		return this.topHeight;
	}

	public void setTopHeight(BigDecimal topHeight) {
		this.topHeight = topHeight;
	}

	@Column(name = "bole_height", precision = 15, scale = 5)
	public BigDecimal getBoleHeight() {
		return this.boleHeight;
	}

	public void setBoleHeight(BigDecimal boleHeight) {
		this.boleHeight = boleHeight;
	}

	@Column(name = "stump_diameter", precision = 15, scale = 5)
	public BigDecimal getStumpDiameter() {
		return this.stumpDiameter;
	}

	public void setStumpDiameter(BigDecimal stumpDiameter) {
		this.stumpDiameter = stumpDiameter;
	}

	@Column(name = "stump_height", precision = 15, scale = 5)
	public BigDecimal getStumpHeight() {
		return this.stumpHeight;
	}

	public void setStumpHeight(BigDecimal stumpHeight) {
		this.stumpHeight = stumpHeight;
	}

	@Column(name = "inclusion_area", precision = 15, scale = 5)
	public BigDecimal getInclusionArea() {
		return this.inclusionArea;
	}

	public void setInclusionArea(BigDecimal inclusionArea) {
		this.inclusionArea = inclusionArea;
	}

	@Column(name = "inclusion_probability", precision = 17, scale = 17)
	public Double getInclusionProbability() {
		return this.inclusionProbability;
	}

	public void setInclusionProbability(Double inclusionProbability) {
		this.inclusionProbability = inclusionProbability;
	}

	@Column(name = "est_top_height", precision = 15, scale = 5)
	public BigDecimal getEstTopHeight() {
		return this.estTopHeight;
	}

	public void setEstTopHeight(BigDecimal estTopHeight) {
		this.estTopHeight = estTopHeight;
	}

	@Column(name = "est_basal_area", precision = 15, scale = 5)
	public BigDecimal getEstBasalArea() {
		return this.estBasalArea;
	}

	public void setEstBasalArea(BigDecimal estBasalArea) {
		this.estBasalArea = estBasalArea;
	}

	@Column(name = "est_stem_volume", precision = 15, scale = 5)
	public BigDecimal getEstStemVolume() {
		return this.estStemVolume;
	}

	public void setEstStemVolume(BigDecimal estStemVolume) {
		this.estStemVolume = estStemVolume;
	}

	@Column(name = "est_bole_volume", precision = 15, scale = 5)
	public BigDecimal getEstBoleVolume() {
		return this.estBoleVolume;
	}

	public void setEstBoleVolume(BigDecimal estBoleVolume) {
		this.estBoleVolume = estBoleVolume;
	}

	@Column(name = "est_top_volume", precision = 15, scale = 5)
	public BigDecimal getEstTopVolume() {
		return this.estTopVolume;
	}

	public void setEstTopVolume(BigDecimal estTopVolume) {
		this.estTopVolume = estTopVolume;
	}

	@Column(name = "est_volume", precision = 15, scale = 5)
	public BigDecimal getEstVolume() {
		return this.estVolume;
	}

	public void setEstVolume(BigDecimal estVolume) {
		this.estVolume = estVolume;
	}

	@Column(name = "est_stem_biomass", precision = 15, scale = 5)
	public BigDecimal getEstStemBiomass() {
		return this.estStemBiomass;
	}

	public void setEstStemBiomass(BigDecimal estStemBiomass) {
		this.estStemBiomass = estStemBiomass;
	}

	@Column(name = "est_ag_biomass", precision = 15, scale = 5)
	public BigDecimal getEstAgBiomass() {
		return this.estAgBiomass;
	}

	public void setEstAgBiomass(BigDecimal estAgBiomass) {
		this.estAgBiomass = estAgBiomass;
	}

	@Column(name = "est_bg_biomass", precision = 15, scale = 5)
	public BigDecimal getEstBgBiomass() {
		return this.estBgBiomass;
	}

	public void setEstBgBiomass(BigDecimal estBgBiomass) {
		this.estBgBiomass = estBgBiomass;
	}

	@Column(name = "est_biomass", precision = 15, scale = 5)
	public BigDecimal getEstBiomass() {
		return this.estBiomass;
	}

	public void setEstBiomass(BigDecimal estBiomass) {
		this.estBiomass = estBiomass;
	}

	@Column(name = "est_stem_carbon", precision = 15, scale = 5)
	public BigDecimal getEstStemCarbon() {
		return this.estStemCarbon;
	}

	public void setEstStemCarbon(BigDecimal estStemCarbon) {
		this.estStemCarbon = estStemCarbon;
	}

	@Column(name = "est_ag_carbon", precision = 15, scale = 5)
	public BigDecimal getEstAgCarbon() {
		return this.estAgCarbon;
	}

	public void setEstAgCarbon(BigDecimal estAgCarbon) {
		this.estAgCarbon = estAgCarbon;
	}

	@Column(name = "est_bg_carbon", precision = 15, scale = 5)
	public BigDecimal getEstBgCarbon() {
		return this.estBgCarbon;
	}

	public void setEstBgCarbon(BigDecimal estBgCarbon) {
		this.estBgCarbon = estBgCarbon;
	}

	@Column(name = "est_carbon", precision = 15, scale = 5)
	public BigDecimal getEstCarbon() {
		return this.estCarbon;
	}

	public void setEstCarbon(BigDecimal estCarbon) {
		this.estCarbon = estCarbon;
	}

}
