/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class CategoryBase implements java.io.Serializable {

	private static final long serialVersionUID = -1054839970;

	private java.lang.Integer id;
	private java.lang.Integer variableId;
	private java.lang.String  code;
	private java.lang.String  defaultLabel;
	private java.lang.Integer order;
	private java.lang.Integer sourceId;
	private java.lang.String  bandingInterval;
	private java.lang.Integer bandingSourceVariableId;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getVariableId() {
		return this.variableId;
	}

	public void setVariableId(java.lang.Integer variableId) {
		this.variableId = variableId;
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.String getDefaultLabel() {
		return this.defaultLabel;
	}

	public void setDefaultLabel(java.lang.String defaultLabel) {
		this.defaultLabel = defaultLabel;
	}

	public java.lang.Integer getOrder() {
		return this.order;
	}

	public void setOrder(java.lang.Integer order) {
		this.order = order;
	}

	public java.lang.Integer getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(java.lang.Integer sourceId) {
		this.sourceId = sourceId;
	}

	public java.lang.String getBandingInterval() {
		return this.bandingInterval;
	}

	public void setBandingInterval(java.lang.String bandingInterval) {
		this.bandingInterval = bandingInterval;
	}

	public java.lang.Integer getBandingSourceVariableId() {
		return this.bandingSourceVariableId;
	}

	public void setBandingSourceVariableId(java.lang.Integer bandingSourceVariableId) {
		this.bandingSourceVariableId = bandingSourceVariableId;
	}
}
