/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class OperationBase implements java.io.Serializable {

	private static final long serialVersionUID = 1283383313;

	private java.lang.Integer id;
	private java.lang.String  name;
	private java.lang.String  description;
	private java.lang.String  class_;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getClass_() {
		return this.class_;
	}

	public void setClass_(java.lang.String class_) {
		this.class_ = class_;
	}
}
