/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class PlotBase implements java.io.Serializable {

	private static final long serialVersionUID = 2100707276;

	private java.lang.Integer id;
	private java.lang.Integer surveyId;
	private java.lang.Integer clusterId;
	private java.lang.Integer no;
	private java.lang.String  code;
	private java.lang.Object  location;
	private java.lang.Object  shape;
	private java.lang.Integer phase;
	private java.lang.Boolean permanentPlot;
	private java.lang.Boolean groundPlot;
	private java.lang.Integer stratumId;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getSurveyId() {
		return this.surveyId;
	}

	public void setSurveyId(java.lang.Integer surveyId) {
		this.surveyId = surveyId;
	}

	public java.lang.Integer getClusterId() {
		return this.clusterId;
	}

	public void setClusterId(java.lang.Integer clusterId) {
		this.clusterId = clusterId;
	}

	public java.lang.Integer getNo() {
		return this.no;
	}

	public void setNo(java.lang.Integer no) {
		this.no = no;
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.Object getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.Object location) {
		this.location = location;
	}

	public java.lang.Object getShape() {
		return this.shape;
	}

	public void setShape(java.lang.Object shape) {
		this.shape = shape;
	}

	public java.lang.Integer getPhase() {
		return this.phase;
	}

	public void setPhase(java.lang.Integer phase) {
		this.phase = phase;
	}

	public java.lang.Boolean getPermanentPlot() {
		return this.permanentPlot;
	}

	public void setPermanentPlot(java.lang.Boolean permanentPlot) {
		this.permanentPlot = permanentPlot;
	}

	public java.lang.Boolean getGroundPlot() {
		return this.groundPlot;
	}

	public void setGroundPlot(java.lang.Boolean groundPlot) {
		this.groundPlot = groundPlot;
	}

	public java.lang.Integer getStratumId() {
		return this.stratumId;
	}

	public void setStratumId(java.lang.Integer stratumId) {
		this.stratumId = stratumId;
	}
}
