/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class PlotCategoryBase implements java.io.Serializable {

	private static final long serialVersionUID = -339192100;

	private java.lang.Integer id;
	private java.lang.Integer plotSurveyId;
	private java.lang.Integer categoryId;
	private java.lang.Boolean computed;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getPlotSurveyId() {
		return this.plotSurveyId;
	}

	public void setPlotSurveyId(java.lang.Integer plotSurveyId) {
		this.plotSurveyId = plotSurveyId;
	}

	public java.lang.Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		this.categoryId = categoryId;
	}

	public java.lang.Boolean getComputed() {
		return this.computed;
	}

	public void setComputed(java.lang.Boolean computed) {
		this.computed = computed;
	}
}
