/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class PlotMeasurementBase implements java.io.Serializable {

	private static final long serialVersionUID = -887924018;

	private java.lang.Integer id;
	private java.lang.Integer plotSurveyId;
	private java.lang.Integer variableId;
	private java.lang.Double  value;
	private java.lang.Boolean computed;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getPlotSurveyId() {
		return this.plotSurveyId;
	}

	public void setPlotSurveyId(java.lang.Integer plotSurveyId) {
		this.plotSurveyId = plotSurveyId;
	}

	public java.lang.Integer getVariableId() {
		return this.variableId;
	}

	public void setVariableId(java.lang.Integer variableId) {
		this.variableId = variableId;
	}

	public java.lang.Double getValue() {
		return this.value;
	}

	public void setValue(java.lang.Double value) {
		this.value = value;
	}

	public java.lang.Boolean getComputed() {
		return this.computed;
	}

	public void setComputed(java.lang.Boolean computed) {
		this.computed = computed;
	}
}
