/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class PlotViewBase implements java.io.Serializable {

	private static final long serialVersionUID = 1351542965;

	private java.lang.Integer surveyId;
	private java.lang.Integer stratumId;
	private java.lang.Integer stratumNo;
	private java.lang.String  stratumCode;
	private java.lang.Integer clusterId;
	private java.lang.Integer clusterNo;
	private java.lang.String  clusterCode;
	private java.lang.Integer clusterX;
	private java.lang.Integer clusterY;
	private java.lang.Integer plotId;
	private java.lang.Integer plotNo;
	private java.lang.String  plotCode;
	private java.lang.Object  location;
	private java.lang.Object  shape;
	private java.lang.Integer phase;
	private java.lang.Boolean groundPlot;
	private java.lang.Boolean permanentPlot;

	public java.lang.Integer getSurveyId() {
		return this.surveyId;
	}

	public void setSurveyId(java.lang.Integer surveyId) {
		this.surveyId = surveyId;
	}

	public java.lang.Integer getStratumId() {
		return this.stratumId;
	}

	public void setStratumId(java.lang.Integer stratumId) {
		this.stratumId = stratumId;
	}

	public java.lang.Integer getStratumNo() {
		return this.stratumNo;
	}

	public void setStratumNo(java.lang.Integer stratumNo) {
		this.stratumNo = stratumNo;
	}

	public java.lang.String getStratumCode() {
		return this.stratumCode;
	}

	public void setStratumCode(java.lang.String stratumCode) {
		this.stratumCode = stratumCode;
	}

	public java.lang.Integer getClusterId() {
		return this.clusterId;
	}

	public void setClusterId(java.lang.Integer clusterId) {
		this.clusterId = clusterId;
	}

	public java.lang.Integer getClusterNo() {
		return this.clusterNo;
	}

	public void setClusterNo(java.lang.Integer clusterNo) {
		this.clusterNo = clusterNo;
	}

	public java.lang.String getClusterCode() {
		return this.clusterCode;
	}

	public void setClusterCode(java.lang.String clusterCode) {
		this.clusterCode = clusterCode;
	}

	public java.lang.Integer getClusterX() {
		return this.clusterX;
	}

	public void setClusterX(java.lang.Integer clusterX) {
		this.clusterX = clusterX;
	}

	public java.lang.Integer getClusterY() {
		return this.clusterY;
	}

	public void setClusterY(java.lang.Integer clusterY) {
		this.clusterY = clusterY;
	}

	public java.lang.Integer getPlotId() {
		return this.plotId;
	}

	public void setPlotId(java.lang.Integer plotId) {
		this.plotId = plotId;
	}

	public java.lang.Integer getPlotNo() {
		return this.plotNo;
	}

	public void setPlotNo(java.lang.Integer plotNo) {
		this.plotNo = plotNo;
	}

	public java.lang.String getPlotCode() {
		return this.plotCode;
	}

	public void setPlotCode(java.lang.String plotCode) {
		this.plotCode = plotCode;
	}

	public java.lang.Object getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.Object location) {
		this.location = location;
	}

	public java.lang.Object getShape() {
		return this.shape;
	}

	public void setShape(java.lang.Object shape) {
		this.shape = shape;
	}

	public java.lang.Integer getPhase() {
		return this.phase;
	}

	public void setPhase(java.lang.Integer phase) {
		this.phase = phase;
	}

	public java.lang.Boolean getGroundPlot() {
		return this.groundPlot;
	}

	public void setGroundPlot(java.lang.Boolean groundPlot) {
		this.groundPlot = groundPlot;
	}

	public java.lang.Boolean getPermanentPlot() {
		return this.permanentPlot;
	}

	public void setPermanentPlot(java.lang.Boolean permanentPlot) {
		this.permanentPlot = permanentPlot;
	}
}
