/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class TaxonVernacularNameBase implements java.io.Serializable {

	private static final long serialVersionUID = 1379408077;

	private java.lang.Integer id;
	private java.lang.Integer acceptedNameId;
	private java.lang.String  name;
	private java.lang.String  languageCode;
	private java.lang.String  languageVariant;
	private java.lang.String  qualifier;
	private java.lang.String  remarks;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getAcceptedNameId() {
		return this.acceptedNameId;
	}

	public void setAcceptedNameId(java.lang.Integer acceptedNameId) {
		this.acceptedNameId = acceptedNameId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(java.lang.String languageCode) {
		this.languageCode = languageCode;
	}

	public java.lang.String getLanguageVariant() {
		return this.languageVariant;
	}

	public void setLanguageVariant(java.lang.String languageVariant) {
		this.languageVariant = languageVariant;
	}

	public java.lang.String getQualifier() {
		return this.qualifier;
	}

	public void setQualifier(java.lang.String qualifier) {
		this.qualifier = qualifier;
	}

	public java.lang.String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(java.lang.String remarks) {
		this.remarks = remarks;
	}
}
