/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class AoiRecord extends org.jooq.impl.UpdatableRecordImpl<org.openforis.calc.persistence.jooq.tables.records.AoiRecord> {

	private static final long serialVersionUID = -738356182;

	/**
	 * The table column <code>calc.aoi.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.ID, value);
	}

	/**
	 * The table column <code>calc.aoi.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.ID);
	}

	/**
	 * The table column <code>calc.aoi.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.AoiRecord> fetchAoiTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI)
			.where(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.PARENT_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.aoi.hierarchy_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT aoi__fk_aoi_hierarchy
	 * FOREIGN KEY (hierarchy_id)
	 * REFERENCES calc.aoi_hierarchy (id)
	 * </pre></code>
	 */
	public void setHierarchyId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.HIERARCHY_ID, value);
	}

	/**
	 * The table column <code>calc.aoi.hierarchy_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT aoi__fk_aoi_hierarchy
	 * FOREIGN KEY (hierarchy_id)
	 * REFERENCES calc.aoi_hierarchy (id)
	 * </pre></code>
	 */
	public java.lang.Integer getHierarchyId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.HIERARCHY_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.AoiHierarchyRecord 
	 * AoiHierarchyRecord}
	 */
	public void setHierarchyId(org.openforis.calc.persistence.jooq.tables.records.AoiHierarchyRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.HIERARCHY_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.HIERARCHY_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.AoiHierarchyTable.AOI_HIERARCHY.ID));
		}
	}

	/**
	 * The table column <code>calc.aoi.hierarchy_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT aoi__fk_aoi_hierarchy
	 * FOREIGN KEY (hierarchy_id)
	 * REFERENCES calc.aoi_hierarchy (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.AoiHierarchyRecord fetchAoiHierarchyTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.AoiHierarchyTable.AOI_HIERARCHY)
			.where(org.openforis.calc.persistence.jooq.tables.AoiHierarchyTable.AOI_HIERARCHY.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.HIERARCHY_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.aoi.code</code>
	 */
	public void setCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.CODE, value);
	}

	/**
	 * The table column <code>calc.aoi.code</code>
	 */
	public java.lang.String getCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.CODE);
	}

	/**
	 * The table column <code>calc.aoi.name</code>
	 */
	public void setName(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.NAME, value);
	}

	/**
	 * The table column <code>calc.aoi.name</code>
	 */
	public java.lang.String getName() {
		return getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.NAME);
	}

	/**
	 * The table column <code>calc.aoi.geometry</code>
	 * <p>
	 * The SQL type of this item (polygon) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setGeometry(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.GEOMETRY, value);
	}

	/**
	 * The table column <code>calc.aoi.geometry</code>
	 * <p>
	 * The SQL type of this item (polygon) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getGeometry() {
		return getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.GEOMETRY);
	}

	/**
	 * The table column <code>calc.aoi.area</code>
	 */
	public void setArea(java.math.BigDecimal value) {
		setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.AREA, value);
	}

	/**
	 * The table column <code>calc.aoi.area</code>
	 */
	public java.math.BigDecimal getArea() {
		return getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.AREA);
	}

	/**
	 * The table column <code>calc.aoi.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT aoi__fk_aoi_parent
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.aoi (id)
	 * </pre></code>
	 */
	public void setParentId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.PARENT_ID, value);
	}

	/**
	 * The table column <code>calc.aoi.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT aoi__fk_aoi_parent
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.aoi (id)
	 * </pre></code>
	 */
	public java.lang.Integer getParentId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.PARENT_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.AoiRecord 
	 * AoiRecord}
	 */
	public void setParentId(org.openforis.calc.persistence.jooq.tables.records.AoiRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.PARENT_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.PARENT_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.ID));
		}
	}

	/**
	 * The table column <code>calc.aoi.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT aoi__fk_aoi_parent
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.aoi (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.AoiRecord fetchAoiTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI)
			.where(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.PARENT_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.aoi.level</code>
	 */
	public void setLevel(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.LEVEL, value);
	}

	/**
	 * The table column <code>calc.aoi.level</code>
	 */
	public java.lang.Integer getLevel() {
		return getValue(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI.LEVEL);
	}

	/**
	 * Create a detached AoiRecord
	 */
	public AoiRecord() {
		super(org.openforis.calc.persistence.jooq.tables.AoiTable.AOI);
	}
}
