/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class CategoryRecord extends org.jooq.impl.UpdatableRecordImpl<org.openforis.calc.persistence.jooq.tables.records.CategoryRecord> {

	private static final long serialVersionUID = 953261453;

	/**
	 * The table column <code>calc.category.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.ID, value);
	}

	/**
	 * The table column <code>calc.category.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.ID);
	}

	/**
	 * The table column <code>calc.category.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord> fetchPlotCategoryTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.PlotCategoryTable.PLOT_CATEGORY)
			.where(org.openforis.calc.persistence.jooq.tables.PlotCategoryTable.PLOT_CATEGORY.CATEGORY_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.category.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.SpecimenCategoryRecord> fetchSpecimenCategoryTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.SpecimenCategoryTable.SPECIMEN_CATEGORY)
			.where(org.openforis.calc.persistence.jooq.tables.SpecimenCategoryTable.SPECIMEN_CATEGORY.CATEGORY_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.category.variable_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT category__fk_category_variable
	 * FOREIGN KEY (variable_id)
	 * REFERENCES calc.variable (id)
	 * </pre></code>
	 */
	public void setVariableId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.VARIABLE_ID, value);
	}

	/**
	 * The table column <code>calc.category.variable_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT category__fk_category_variable
	 * FOREIGN KEY (variable_id)
	 * REFERENCES calc.variable (id)
	 * </pre></code>
	 */
	public java.lang.Integer getVariableId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.VARIABLE_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.VariableRecord 
	 * VariableRecord}
	 */
	public void setVariableId(org.openforis.calc.persistence.jooq.tables.records.VariableRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.VARIABLE_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.VARIABLE_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE.ID));
		}
	}

	/**
	 * The table column <code>calc.category.variable_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT category__fk_category_variable
	 * FOREIGN KEY (variable_id)
	 * REFERENCES calc.variable (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.VariableRecord fetchVariableTableByVariableIdTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE)
			.where(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.VARIABLE_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.category.code</code>
	 */
	public void setCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.CODE, value);
	}

	/**
	 * The table column <code>calc.category.code</code>
	 */
	public java.lang.String getCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.CODE);
	}

	/**
	 * The table column <code>calc.category.default_label</code>
	 */
	public void setDefaultLabel(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.DEFAULT_LABEL, value);
	}

	/**
	 * The table column <code>calc.category.default_label</code>
	 */
	public java.lang.String getDefaultLabel() {
		return getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.DEFAULT_LABEL);
	}

	/**
	 * The table column <code>calc.category.order</code>
	 */
	public void setOrder(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.ORDER, value);
	}

	/**
	 * The table column <code>calc.category.order</code>
	 */
	public java.lang.Integer getOrder() {
		return getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.ORDER);
	}

	/**
	 * The table column <code>calc.category.source_id</code>
	 */
	public void setSourceId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.SOURCE_ID, value);
	}

	/**
	 * The table column <code>calc.category.source_id</code>
	 */
	public java.lang.Integer getSourceId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.SOURCE_ID);
	}

	/**
	 * The table column <code>calc.category.banding_interval</code>
	 */
	public void setBandingInterval(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.BANDING_INTERVAL, value);
	}

	/**
	 * The table column <code>calc.category.banding_interval</code>
	 */
	public java.lang.String getBandingInterval() {
		return getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.BANDING_INTERVAL);
	}

	/**
	 * The table column <code>calc.category.banding_source_variable_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT category__fk_category_banding_source_variable
	 * FOREIGN KEY (banding_source_variable_id)
	 * REFERENCES calc.variable (id)
	 * </pre></code>
	 */
	public void setBandingSourceVariableId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.BANDING_SOURCE_VARIABLE_ID, value);
	}

	/**
	 * The table column <code>calc.category.banding_source_variable_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT category__fk_category_banding_source_variable
	 * FOREIGN KEY (banding_source_variable_id)
	 * REFERENCES calc.variable (id)
	 * </pre></code>
	 */
	public java.lang.Integer getBandingSourceVariableId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.BANDING_SOURCE_VARIABLE_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.VariableRecord 
	 * VariableRecord}
	 */
	public void setBandingSourceVariableId(org.openforis.calc.persistence.jooq.tables.records.VariableRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.BANDING_SOURCE_VARIABLE_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.BANDING_SOURCE_VARIABLE_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE.ID));
		}
	}

	/**
	 * The table column <code>calc.category.banding_source_variable_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT category__fk_category_banding_source_variable
	 * FOREIGN KEY (banding_source_variable_id)
	 * REFERENCES calc.variable (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.VariableRecord fetchVariableTableByBandingSourceVariableIdTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE)
			.where(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY.BANDING_SOURCE_VARIABLE_ID)))
			.fetchOne();
	}

	/**
	 * Create a detached CategoryRecord
	 */
	public CategoryRecord() {
		super(org.openforis.calc.persistence.jooq.tables.CategoryTable.CATEGORY);
	}
}
