/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class GroundPlotViewRecord extends org.jooq.impl.TableRecordImpl<org.openforis.calc.persistence.jooq.tables.records.GroundPlotViewRecord> {

	private static final long serialVersionUID = -908821591;

	/**
	 * The table column <code>calc.ground_plot_view.survey_id</code>
	 */
	public void setSurveyId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.SURVEY_ID, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.survey_id</code>
	 */
	public java.lang.Integer getSurveyId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.SURVEY_ID);
	}

	/**
	 * The table column <code>calc.ground_plot_view.stratum_id</code>
	 */
	public void setStratumId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.STRATUM_ID, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.stratum_id</code>
	 */
	public java.lang.Integer getStratumId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.STRATUM_ID);
	}

	/**
	 * The table column <code>calc.ground_plot_view.stratum_no</code>
	 */
	public void setStratumNo(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.STRATUM_NO, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.stratum_no</code>
	 */
	public java.lang.Integer getStratumNo() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.STRATUM_NO);
	}

	/**
	 * The table column <code>calc.ground_plot_view.stratum_code</code>
	 */
	public void setStratumCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.STRATUM_CODE, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.stratum_code</code>
	 */
	public java.lang.String getStratumCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.STRATUM_CODE);
	}

	/**
	 * The table column <code>calc.ground_plot_view.cluster_id</code>
	 */
	public void setClusterId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.CLUSTER_ID, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.cluster_id</code>
	 */
	public java.lang.Integer getClusterId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.CLUSTER_ID);
	}

	/**
	 * The table column <code>calc.ground_plot_view.cluster_no</code>
	 */
	public void setClusterNo(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.CLUSTER_NO, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.cluster_no</code>
	 */
	public java.lang.Integer getClusterNo() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.CLUSTER_NO);
	}

	/**
	 * The table column <code>calc.ground_plot_view.cluster_code</code>
	 */
	public void setClusterCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.CLUSTER_CODE, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.cluster_code</code>
	 */
	public java.lang.String getClusterCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.CLUSTER_CODE);
	}

	/**
	 * The table column <code>calc.ground_plot_view.cluster_x</code>
	 */
	public void setClusterX(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.CLUSTER_X, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.cluster_x</code>
	 */
	public java.lang.Integer getClusterX() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.CLUSTER_X);
	}

	/**
	 * The table column <code>calc.ground_plot_view.cluster_y</code>
	 */
	public void setClusterY(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.CLUSTER_Y, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.cluster_y</code>
	 */
	public java.lang.Integer getClusterY() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.CLUSTER_Y);
	}

	/**
	 * The table column <code>calc.ground_plot_view.plot_id</code>
	 */
	public void setPlotId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.PLOT_ID, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.plot_id</code>
	 */
	public java.lang.Integer getPlotId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.PLOT_ID);
	}

	/**
	 * The table column <code>calc.ground_plot_view.plot_no</code>
	 */
	public void setPlotNo(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.PLOT_NO, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.plot_no</code>
	 */
	public java.lang.Integer getPlotNo() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.PLOT_NO);
	}

	/**
	 * The table column <code>calc.ground_plot_view.plot_code</code>
	 */
	public void setPlotCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.PLOT_CODE, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.plot_code</code>
	 */
	public java.lang.String getPlotCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.PLOT_CODE);
	}

	/**
	 * The table column <code>calc.ground_plot_view.location</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setLocation(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.LOCATION, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.location</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getLocation() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.LOCATION);
	}

	/**
	 * The table column <code>calc.ground_plot_view.shape</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setShape(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.SHAPE, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.shape</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getShape() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.SHAPE);
	}

	/**
	 * The table column <code>calc.ground_plot_view.phase</code>
	 */
	public void setPhase(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.PHASE, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.phase</code>
	 */
	public java.lang.Integer getPhase() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.PHASE);
	}

	/**
	 * The table column <code>calc.ground_plot_view.ground_plot</code>
	 */
	public void setGroundPlot(java.lang.Boolean value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.GROUND_PLOT, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.ground_plot</code>
	 */
	public java.lang.Boolean getGroundPlot() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.GROUND_PLOT);
	}

	/**
	 * The table column <code>calc.ground_plot_view.permanent_plot</code>
	 */
	public void setPermanentPlot(java.lang.Boolean value) {
		setValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.PERMANENT_PLOT, value);
	}

	/**
	 * The table column <code>calc.ground_plot_view.permanent_plot</code>
	 */
	public java.lang.Boolean getPermanentPlot() {
		return getValue(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW.PERMANENT_PLOT);
	}

	/**
	 * Create a detached GroundPlotViewRecord
	 */
	public GroundPlotViewRecord() {
		super(org.openforis.calc.persistence.jooq.tables.GroundPlotViewTable.GROUND_PLOT_VIEW);
	}
}
