/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class ObservationUnitRecord extends org.jooq.impl.UpdatableRecordImpl<org.openforis.calc.persistence.jooq.tables.records.ObservationUnitRecord> {

	private static final long serialVersionUID = -1581551827;

	/**
	 * The table column <code>calc.observation_unit.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.ID, value);
	}

	/**
	 * The table column <code>calc.observation_unit.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.ID);
	}

	/**
	 * The table column <code>calc.observation_unit.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.ObservationUnitRecord> fetchObservationUnitTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT)
			.where(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.PARENT_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.observation_unit.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.PlotSurveyRecord> fetchPlotSurveyTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY)
			.where(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.OBS_UNIT_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.observation_unit.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord> fetchSpecimenTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.SpecimenTable.SPECIMEN)
			.where(org.openforis.calc.persistence.jooq.tables.SpecimenTable.SPECIMEN.OBS_UNIT_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.observation_unit.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.VariableRecord> fetchVariableTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE)
			.where(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE.OBS_UNIT_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.observation_unit.survey_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT observation_unit__fk_obs_unit_survey
	 * FOREIGN KEY (survey_id)
	 * REFERENCES calc.survey (id)
	 * </pre></code>
	 */
	public void setSurveyId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.SURVEY_ID, value);
	}

	/**
	 * The table column <code>calc.observation_unit.survey_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT observation_unit__fk_obs_unit_survey
	 * FOREIGN KEY (survey_id)
	 * REFERENCES calc.survey (id)
	 * </pre></code>
	 */
	public java.lang.Integer getSurveyId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.SURVEY_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.SurveyRecord 
	 * SurveyRecord}
	 */
	public void setSurveyId(org.openforis.calc.persistence.jooq.tables.records.SurveyRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.SURVEY_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.SURVEY_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.SurveyTable.SURVEY.ID));
		}
	}

	/**
	 * The table column <code>calc.observation_unit.survey_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT observation_unit__fk_obs_unit_survey
	 * FOREIGN KEY (survey_id)
	 * REFERENCES calc.survey (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.SurveyRecord fetchSurveyTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.SurveyTable.SURVEY)
			.where(org.openforis.calc.persistence.jooq.tables.SurveyTable.SURVEY.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.SURVEY_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.observation_unit.name</code>
	 */
	public void setName(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.NAME, value);
	}

	/**
	 * The table column <code>calc.observation_unit.name</code>
	 */
	public java.lang.String getName() {
		return getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.NAME);
	}

	/**
	 * The table column <code>calc.observation_unit.type</code>
	 */
	public void setType(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.TYPE, value);
	}

	/**
	 * The table column <code>calc.observation_unit.type</code>
	 */
	public java.lang.String getType() {
		return getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.TYPE);
	}

	/**
	 * The table column <code>calc.observation_unit.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT observation_unit__fk_obs_unit_parent
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.observation_unit (id)
	 * </pre></code>
	 */
	public void setParentId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.PARENT_ID, value);
	}

	/**
	 * The table column <code>calc.observation_unit.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT observation_unit__fk_obs_unit_parent
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.observation_unit (id)
	 * </pre></code>
	 */
	public java.lang.Integer getParentId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.PARENT_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.ObservationUnitRecord 
	 * ObservationUnitRecord}
	 */
	public void setParentId(org.openforis.calc.persistence.jooq.tables.records.ObservationUnitRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.PARENT_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.PARENT_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.ID));
		}
	}

	/**
	 * The table column <code>calc.observation_unit.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT observation_unit__fk_obs_unit_parent
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.observation_unit (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.ObservationUnitRecord fetchObservationUnitTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT)
			.where(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.PARENT_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.observation_unit.source_id</code>
	 */
	public void setSourceId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.SOURCE_ID, value);
	}

	/**
	 * The table column <code>calc.observation_unit.source_id</code>
	 */
	public java.lang.Integer getSourceId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.SOURCE_ID);
	}

	/**
	 * Create a detached ObservationUnitRecord
	 */
	public ObservationUnitRecord() {
		super(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT);
	}
}
