/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class OperationRecord extends org.jooq.impl.UpdatableRecordImpl<org.openforis.calc.persistence.jooq.tables.records.OperationRecord> {

	private static final long serialVersionUID = -420858486;

	/**
	 * The table column <code>calc.operation.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION.ID, value);
	}

	/**
	 * The table column <code>calc.operation.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION.ID);
	}

	/**
	 * The table column <code>calc.operation.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.ProcessRecord> fetchProcessTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.ProcessTable.PROCESS)
			.where(org.openforis.calc.persistence.jooq.tables.ProcessTable.PROCESS.OPERATION_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.operation.name</code>
	 */
	public void setName(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION.NAME, value);
	}

	/**
	 * The table column <code>calc.operation.name</code>
	 */
	public java.lang.String getName() {
		return getValue(org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION.NAME);
	}

	/**
	 * The table column <code>calc.operation.description</code>
	 */
	public void setDescription(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION.DESCRIPTION, value);
	}

	/**
	 * The table column <code>calc.operation.description</code>
	 */
	public java.lang.String getDescription() {
		return getValue(org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION.DESCRIPTION);
	}

	/**
	 * The table column <code>calc.operation.class</code>
	 */
	public void setClass_(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION.CLASS, value);
	}

	/**
	 * The table column <code>calc.operation.class</code>
	 */
	public java.lang.String getClass_() {
		return getValue(org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION.CLASS);
	}

	/**
	 * Create a detached OperationRecord
	 */
	public OperationRecord() {
		super(org.openforis.calc.persistence.jooq.tables.OperationTable.OPERATION);
	}
}
