/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class PlotCategoryViewRecord extends org.jooq.impl.TableRecordImpl<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryViewRecord> {

	private static final long serialVersionUID = -571717039;

	/**
	 * The table column <code>calc.plot_category_view.survey_id</code>
	 */
	public void setSurveyId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.SURVEY_ID, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.survey_id</code>
	 */
	public java.lang.Integer getSurveyId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.SURVEY_ID);
	}

	/**
	 * The table column <code>calc.plot_category_view.stratum_id</code>
	 */
	public void setStratumId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.STRATUM_ID, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.stratum_id</code>
	 */
	public java.lang.Integer getStratumId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.STRATUM_ID);
	}

	/**
	 * The table column <code>calc.plot_category_view.stratum_no</code>
	 */
	public void setStratumNo(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.STRATUM_NO, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.stratum_no</code>
	 */
	public java.lang.Integer getStratumNo() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.STRATUM_NO);
	}

	/**
	 * The table column <code>calc.plot_category_view.stratum_code</code>
	 */
	public void setStratumCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.STRATUM_CODE, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.stratum_code</code>
	 */
	public java.lang.String getStratumCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.STRATUM_CODE);
	}

	/**
	 * The table column <code>calc.plot_category_view.cluster_id</code>
	 */
	public void setClusterId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CLUSTER_ID, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.cluster_id</code>
	 */
	public java.lang.Integer getClusterId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CLUSTER_ID);
	}

	/**
	 * The table column <code>calc.plot_category_view.cluster_no</code>
	 */
	public void setClusterNo(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CLUSTER_NO, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.cluster_no</code>
	 */
	public java.lang.Integer getClusterNo() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CLUSTER_NO);
	}

	/**
	 * The table column <code>calc.plot_category_view.cluster_code</code>
	 */
	public void setClusterCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CLUSTER_CODE, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.cluster_code</code>
	 */
	public java.lang.String getClusterCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CLUSTER_CODE);
	}

	/**
	 * The table column <code>calc.plot_category_view.cluster_x</code>
	 */
	public void setClusterX(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CLUSTER_X, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.cluster_x</code>
	 */
	public java.lang.Integer getClusterX() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CLUSTER_X);
	}

	/**
	 * The table column <code>calc.plot_category_view.cluster_y</code>
	 */
	public void setClusterY(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CLUSTER_Y, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.cluster_y</code>
	 */
	public java.lang.Integer getClusterY() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CLUSTER_Y);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_id</code>
	 */
	public void setPlotId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_ID, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_id</code>
	 */
	public java.lang.Integer getPlotId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_ID);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_survey_parent_id</code>
	 */
	public void setPlotSurveyParentId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_SURVEY_PARENT_ID, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_survey_parent_id</code>
	 */
	public java.lang.Integer getPlotSurveyParentId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_SURVEY_PARENT_ID);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_no</code>
	 */
	public void setPlotNo(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_NO, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_no</code>
	 */
	public java.lang.Integer getPlotNo() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_NO);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_code</code>
	 */
	public void setPlotCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_CODE, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_code</code>
	 */
	public java.lang.String getPlotCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_CODE);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_survey_id</code>
	 */
	public void setPlotSurveyId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_SURVEY_ID, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_survey_id</code>
	 */
	public java.lang.Integer getPlotSurveyId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_SURVEY_ID);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_section</code>
	 */
	public void setPlotSection(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_SECTION, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.plot_section</code>
	 */
	public java.lang.Integer getPlotSection() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.PLOT_SECTION);
	}

	/**
	 * The table column <code>calc.plot_category_view.survey_type</code>
	 */
	public void setSurveyType(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.SURVEY_TYPE, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.survey_type</code>
	 */
	public java.lang.String getSurveyType() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.SURVEY_TYPE);
	}

	/**
	 * The table column <code>calc.plot_category_view.obs_unit_id</code>
	 */
	public void setObsUnitId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.OBS_UNIT_ID, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.obs_unit_id</code>
	 */
	public java.lang.Integer getObsUnitId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.OBS_UNIT_ID);
	}

	/**
	 * The table column <code>calc.plot_category_view.obs_unit_name</code>
	 */
	public void setObsUnitName(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.OBS_UNIT_NAME, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.obs_unit_name</code>
	 */
	public java.lang.String getObsUnitName() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.OBS_UNIT_NAME);
	}

	/**
	 * The table column <code>calc.plot_category_view.step</code>
	 */
	public void setStep(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.STEP, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.step</code>
	 */
	public java.lang.Integer getStep() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.STEP);
	}

	/**
	 * The table column <code>calc.plot_category_view.variable_name</code>
	 */
	public void setVariableName(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.VARIABLE_NAME, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.variable_name</code>
	 */
	public java.lang.String getVariableName() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.VARIABLE_NAME);
	}

	/**
	 * The table column <code>calc.plot_category_view.category_code</code>
	 */
	public void setCategoryCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CATEGORY_CODE, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.category_code</code>
	 */
	public java.lang.String getCategoryCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.CATEGORY_CODE);
	}

	/**
	 * The table column <code>calc.plot_category_view.computed</code>
	 */
	public void setComputed(java.lang.Boolean value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.COMPUTED, value);
	}

	/**
	 * The table column <code>calc.plot_category_view.computed</code>
	 */
	public java.lang.Boolean getComputed() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW.COMPUTED);
	}

	/**
	 * Create a detached PlotCategoryViewRecord
	 */
	public PlotCategoryViewRecord() {
		super(org.openforis.calc.persistence.jooq.tables.PlotCategoryViewTable.PLOT_CATEGORY_VIEW);
	}
}
