/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class PlotSurveyRecord extends org.jooq.impl.UpdatableRecordImpl<org.openforis.calc.persistence.jooq.tables.records.PlotSurveyRecord> {

	private static final long serialVersionUID = -247753926;

	/**
	 * The table column <code>calc.plot_survey.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.ID);
	}

	/**
	 * The table column <code>calc.plot_survey.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord> fetchPlotCategoryTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.PlotCategoryTable.PLOT_CATEGORY)
			.where(org.openforis.calc.persistence.jooq.tables.PlotCategoryTable.PLOT_CATEGORY.PLOT_SURVEY_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.plot_survey.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementRecord> fetchPlotMeasurementTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.PlotMeasurementTable.PLOT_MEASUREMENT)
			.where(org.openforis.calc.persistence.jooq.tables.PlotMeasurementTable.PLOT_MEASUREMENT.PLOT_SURVEY_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.plot_survey.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.PlotSurveyRecord> fetchPlotSurveyTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY)
			.where(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PARENT_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.plot_survey.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord> fetchSpecimenTableList() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.SpecimenTable.SPECIMEN)
			.where(org.openforis.calc.persistence.jooq.tables.SpecimenTable.SPECIMEN.PLOT_ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.ID)))
			.fetch();
	}

	/**
	 * The table column <code>calc.plot_survey.survey_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_plot_survey_survey
	 * FOREIGN KEY (survey_id)
	 * REFERENCES calc.survey (id)
	 * </pre></code>
	 */
	public void setSurveyId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SURVEY_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey.survey_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_plot_survey_survey
	 * FOREIGN KEY (survey_id)
	 * REFERENCES calc.survey (id)
	 * </pre></code>
	 */
	public java.lang.Integer getSurveyId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SURVEY_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.SurveyRecord 
	 * SurveyRecord}
	 */
	public void setSurveyId(org.openforis.calc.persistence.jooq.tables.records.SurveyRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SURVEY_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SURVEY_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.SurveyTable.SURVEY.ID));
		}
	}

	/**
	 * The table column <code>calc.plot_survey.survey_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_plot_survey_survey
	 * FOREIGN KEY (survey_id)
	 * REFERENCES calc.survey (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.SurveyRecord fetchSurveyTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.SurveyTable.SURVEY)
			.where(org.openforis.calc.persistence.jooq.tables.SurveyTable.SURVEY.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SURVEY_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.plot_survey.plot_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_plot_survey_plot
	 * FOREIGN KEY (plot_id)
	 * REFERENCES calc.plot (id)
	 * </pre></code>
	 */
	public void setPlotId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PLOT_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey.plot_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_plot_survey_plot
	 * FOREIGN KEY (plot_id)
	 * REFERENCES calc.plot (id)
	 * </pre></code>
	 */
	public java.lang.Integer getPlotId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PLOT_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.PlotRecord 
	 * PlotRecord}
	 */
	public void setPlotId(org.openforis.calc.persistence.jooq.tables.records.PlotRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PLOT_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PLOT_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.PlotTable.PLOT.ID));
		}
	}

	/**
	 * The table column <code>calc.plot_survey.plot_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_plot_survey_plot
	 * FOREIGN KEY (plot_id)
	 * REFERENCES calc.plot (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.PlotRecord fetchPlotTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.PlotTable.PLOT)
			.where(org.openforis.calc.persistence.jooq.tables.PlotTable.PLOT.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PLOT_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.plot_survey.obs_unit_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_plot_survey_obs_unit
	 * FOREIGN KEY (obs_unit_id)
	 * REFERENCES calc.observation_unit (id)
	 * </pre></code>
	 */
	public void setObsUnitId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.OBS_UNIT_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey.obs_unit_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_plot_survey_obs_unit
	 * FOREIGN KEY (obs_unit_id)
	 * REFERENCES calc.observation_unit (id)
	 * </pre></code>
	 */
	public java.lang.Integer getObsUnitId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.OBS_UNIT_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.ObservationUnitRecord 
	 * ObservationUnitRecord}
	 */
	public void setObsUnitId(org.openforis.calc.persistence.jooq.tables.records.ObservationUnitRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.OBS_UNIT_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.OBS_UNIT_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.ID));
		}
	}

	/**
	 * The table column <code>calc.plot_survey.obs_unit_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_plot_survey_obs_unit
	 * FOREIGN KEY (obs_unit_id)
	 * REFERENCES calc.observation_unit (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.ObservationUnitRecord fetchObservationUnitTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT)
			.where(org.openforis.calc.persistence.jooq.tables.ObservationUnitTable.OBSERVATION_UNIT.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.OBS_UNIT_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.plot_survey.section_no</code>
	 */
	public void setSectionNo(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SECTION_NO, value);
	}

	/**
	 * The table column <code>calc.plot_survey.section_no</code>
	 */
	public java.lang.Integer getSectionNo() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SECTION_NO);
	}

	/**
	 * The table column <code>calc.plot_survey.survey_date</code>
	 */
	public void setSurveyDate(java.sql.Date value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SURVEY_DATE, value);
	}

	/**
	 * The table column <code>calc.plot_survey.survey_date</code>
	 */
	public java.sql.Date getSurveyDate() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SURVEY_DATE);
	}

	/**
	 * The table column <code>calc.plot_survey.gps_reading</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setGpsReading(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.GPS_READING, value);
	}

	/**
	 * The table column <code>calc.plot_survey.gps_reading</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getGpsReading() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.GPS_READING);
	}

	/**
	 * The table column <code>calc.plot_survey.direction</code>
	 */
	public void setDirection(java.lang.Double value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.DIRECTION, value);
	}

	/**
	 * The table column <code>calc.plot_survey.direction</code>
	 */
	public java.lang.Double getDirection() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.DIRECTION);
	}

	/**
	 * The table column <code>calc.plot_survey.distance</code>
	 */
	public void setDistance(java.lang.Double value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.DISTANCE, value);
	}

	/**
	 * The table column <code>calc.plot_survey.distance</code>
	 */
	public java.lang.Double getDistance() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.DISTANCE);
	}

	/**
	 * The table column <code>calc.plot_survey.location</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setLocation(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.LOCATION, value);
	}

	/**
	 * The table column <code>calc.plot_survey.location</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getLocation() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.LOCATION);
	}

	/**
	 * The table column <code>calc.plot_survey.accessible</code>
	 */
	public void setAccessible(java.lang.Boolean value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.ACCESSIBLE, value);
	}

	/**
	 * The table column <code>calc.plot_survey.accessible</code>
	 */
	public java.lang.Boolean getAccessible() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.ACCESSIBLE);
	}

	/**
	 * The table column <code>calc.plot_survey.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_parent_plot_survey
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.plot_survey (id)
	 * </pre></code>
	 */
	public void setParentId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PARENT_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_parent_plot_survey
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.plot_survey (id)
	 * </pre></code>
	 */
	public java.lang.Integer getParentId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PARENT_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.PlotSurveyRecord 
	 * PlotSurveyRecord}
	 */
	public void setParentId(org.openforis.calc.persistence.jooq.tables.records.PlotSurveyRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PARENT_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PARENT_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.ID));
		}
	}

	/**
	 * The table column <code>calc.plot_survey.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_survey__fk_parent_plot_survey
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.plot_survey (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.PlotSurveyRecord fetchPlotSurveyTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY)
			.where(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PARENT_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.plot_survey.survey_type</code>
	 */
	public void setSurveyType(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SURVEY_TYPE, value);
	}

	/**
	 * The table column <code>calc.plot_survey.survey_type</code>
	 */
	public java.lang.String getSurveyType() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SURVEY_TYPE);
	}

	/**
	 * The table column <code>calc.plot_survey.step</code>
	 */
	public void setStep(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.STEP, value);
	}

	/**
	 * The table column <code>calc.plot_survey.step</code>
	 */
	public java.lang.Integer getStep() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.STEP);
	}

	/**
	 * The table column <code>calc.plot_survey.source_id</code>
	 */
	public void setSourceId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SOURCE_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey.source_id</code>
	 */
	public java.lang.Integer getSourceId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SOURCE_ID);
	}

	/**
	 * The table column <code>calc.plot_survey.shape</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setShape(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SHAPE, value);
	}

	/**
	 * The table column <code>calc.plot_survey.shape</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getShape() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.SHAPE);
	}

	/**
	 * The table column <code>calc.plot_survey.area</code>
	 */
	public void setArea(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.AREA, value);
	}

	/**
	 * The table column <code>calc.plot_survey.area</code>
	 */
	public java.lang.Integer getArea() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.AREA);
	}

	/**
	 * The table column <code>calc.plot_survey.percent_share</code>
	 */
	public void setPercentShare(java.lang.Double value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PERCENT_SHARE, value);
	}

	/**
	 * The table column <code>calc.plot_survey.percent_share</code>
	 */
	public java.lang.Double getPercentShare() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY.PERCENT_SHARE);
	}

	/**
	 * Create a detached PlotSurveyRecord
	 */
	public PlotSurveyRecord() {
		super(org.openforis.calc.persistence.jooq.tables.PlotSurveyTable.PLOT_SURVEY);
	}
}
