/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class PlotSurveyViewRecord extends org.jooq.impl.TableRecordImpl<org.openforis.calc.persistence.jooq.tables.records.PlotSurveyViewRecord> {

	private static final long serialVersionUID = 820977005;

	/**
	 * The table column <code>calc.plot_survey_view.survey_id</code>
	 */
	public void setSurveyId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.SURVEY_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.survey_id</code>
	 */
	public java.lang.Integer getSurveyId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.SURVEY_ID);
	}

	/**
	 * The table column <code>calc.plot_survey_view.stratum_id</code>
	 */
	public void setStratumId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.STRATUM_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.stratum_id</code>
	 */
	public java.lang.Integer getStratumId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.STRATUM_ID);
	}

	/**
	 * The table column <code>calc.plot_survey_view.stratum_no</code>
	 */
	public void setStratumNo(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.STRATUM_NO, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.stratum_no</code>
	 */
	public java.lang.Integer getStratumNo() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.STRATUM_NO);
	}

	/**
	 * The table column <code>calc.plot_survey_view.stratum_code</code>
	 */
	public void setStratumCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.STRATUM_CODE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.stratum_code</code>
	 */
	public java.lang.String getStratumCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.STRATUM_CODE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.cluster_id</code>
	 */
	public void setClusterId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.CLUSTER_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.cluster_id</code>
	 */
	public java.lang.Integer getClusterId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.CLUSTER_ID);
	}

	/**
	 * The table column <code>calc.plot_survey_view.cluster_no</code>
	 */
	public void setClusterNo(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.CLUSTER_NO, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.cluster_no</code>
	 */
	public java.lang.Integer getClusterNo() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.CLUSTER_NO);
	}

	/**
	 * The table column <code>calc.plot_survey_view.cluster_code</code>
	 */
	public void setClusterCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.CLUSTER_CODE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.cluster_code</code>
	 */
	public java.lang.String getClusterCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.CLUSTER_CODE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.cluster_x</code>
	 */
	public void setClusterX(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.CLUSTER_X, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.cluster_x</code>
	 */
	public java.lang.Integer getClusterX() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.CLUSTER_X);
	}

	/**
	 * The table column <code>calc.plot_survey_view.cluster_y</code>
	 */
	public void setClusterY(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.CLUSTER_Y, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.cluster_y</code>
	 */
	public java.lang.Integer getClusterY() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.CLUSTER_Y);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_id</code>
	 */
	public void setPlotId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_id</code>
	 */
	public java.lang.Integer getPlotId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_ID);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_no</code>
	 */
	public void setPlotNo(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_NO, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_no</code>
	 */
	public java.lang.Integer getPlotNo() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_NO);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_code</code>
	 */
	public void setPlotCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_CODE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_code</code>
	 */
	public java.lang.String getPlotCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_CODE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.location</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setLocation(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.LOCATION, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.location</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getLocation() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.LOCATION);
	}

	/**
	 * The table column <code>calc.plot_survey_view.shape</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setShape(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.SHAPE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.shape</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getShape() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.SHAPE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.phase</code>
	 */
	public void setPhase(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PHASE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.phase</code>
	 */
	public java.lang.Integer getPhase() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PHASE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.ground_plot</code>
	 */
	public void setGroundPlot(java.lang.Boolean value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.GROUND_PLOT, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.ground_plot</code>
	 */
	public java.lang.Boolean getGroundPlot() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.GROUND_PLOT);
	}

	/**
	 * The table column <code>calc.plot_survey_view.permanent_plot</code>
	 */
	public void setPermanentPlot(java.lang.Boolean value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PERMANENT_PLOT, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.permanent_plot</code>
	 */
	public java.lang.Boolean getPermanentPlot() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PERMANENT_PLOT);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_survey_id</code>
	 */
	public void setPlotSurveyId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_SURVEY_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_survey_id</code>
	 */
	public java.lang.Integer getPlotSurveyId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_SURVEY_ID);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_section</code>
	 */
	public void setPlotSection(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_SECTION, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_section</code>
	 */
	public java.lang.Integer getPlotSection() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_SECTION);
	}

	/**
	 * The table column <code>calc.plot_survey_view.survey_date</code>
	 */
	public void setSurveyDate(java.sql.Date value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.SURVEY_DATE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.survey_date</code>
	 */
	public java.sql.Date getSurveyDate() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.SURVEY_DATE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.gps_reading</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setGpsReading(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.GPS_READING, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.gps_reading</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getGpsReading() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.GPS_READING);
	}

	/**
	 * The table column <code>calc.plot_survey_view.direction</code>
	 */
	public void setDirection(java.lang.Double value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.DIRECTION, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.direction</code>
	 */
	public java.lang.Double getDirection() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.DIRECTION);
	}

	/**
	 * The table column <code>calc.plot_survey_view.distance</code>
	 */
	public void setDistance(java.lang.Double value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.DISTANCE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.distance</code>
	 */
	public java.lang.Double getDistance() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.DISTANCE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.survey_location</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setSurveyLocation(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.SURVEY_LOCATION, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.survey_location</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getSurveyLocation() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.SURVEY_LOCATION);
	}

	/**
	 * The table column <code>calc.plot_survey_view.accessible</code>
	 */
	public void setAccessible(java.lang.Boolean value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.ACCESSIBLE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.accessible</code>
	 */
	public java.lang.Boolean getAccessible() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.ACCESSIBLE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_survey_parent_id</code>
	 */
	public void setPlotSurveyParentId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_SURVEY_PARENT_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_survey_parent_id</code>
	 */
	public java.lang.Integer getPlotSurveyParentId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_SURVEY_PARENT_ID);
	}

	/**
	 * The table column <code>calc.plot_survey_view.survey_type</code>
	 */
	public void setSurveyType(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.SURVEY_TYPE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.survey_type</code>
	 */
	public java.lang.String getSurveyType() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.SURVEY_TYPE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.step</code>
	 */
	public void setStep(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.STEP, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.step</code>
	 */
	public java.lang.Integer getStep() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.STEP);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_survey_shape</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public void setPlotSurveyShape(java.lang.Object value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_SURVEY_SHAPE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_survey_shape</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, geometry) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public java.lang.Object getPlotSurveyShape() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_SURVEY_SHAPE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_survey_area</code>
	 */
	public void setPlotSurveyArea(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_SURVEY_AREA, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.plot_survey_area</code>
	 */
	public java.lang.Integer getPlotSurveyArea() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PLOT_SURVEY_AREA);
	}

	/**
	 * The table column <code>calc.plot_survey_view.percent_share</code>
	 */
	public void setPercentShare(java.lang.Double value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PERCENT_SHARE, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.percent_share</code>
	 */
	public java.lang.Double getPercentShare() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.PERCENT_SHARE);
	}

	/**
	 * The table column <code>calc.plot_survey_view.obs_unit_id</code>
	 */
	public void setObsUnitId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.OBS_UNIT_ID, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.obs_unit_id</code>
	 */
	public java.lang.Integer getObsUnitId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.OBS_UNIT_ID);
	}

	/**
	 * The table column <code>calc.plot_survey_view.obs_unit_name</code>
	 */
	public void setObsUnitName(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.OBS_UNIT_NAME, value);
	}

	/**
	 * The table column <code>calc.plot_survey_view.obs_unit_name</code>
	 */
	public java.lang.String getObsUnitName() {
		return getValue(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW.OBS_UNIT_NAME);
	}

	/**
	 * Create a detached PlotSurveyViewRecord
	 */
	public PlotSurveyViewRecord() {
		super(org.openforis.calc.persistence.jooq.tables.PlotSurveyViewTable.PLOT_SURVEY_VIEW);
	}
}
