/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class SpecimenMeasurementRecord extends org.jooq.impl.UpdatableRecordImpl<org.openforis.calc.persistence.jooq.tables.records.SpecimenMeasurementRecord> {

	private static final long serialVersionUID = 417330732;

	/**
	 * The table column <code>calc.specimen_measurement.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.ID, value);
	}

	/**
	 * The table column <code>calc.specimen_measurement.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.ID);
	}

	/**
	 * The table column <code>calc.specimen_measurement.specimen_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT specimen_measurement__fk_specimen_measurement_specimen
	 * FOREIGN KEY (specimen_id)
	 * REFERENCES calc.specimen (id)
	 * </pre></code>
	 */
	public void setSpecimenId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.SPECIMEN_ID, value);
	}

	/**
	 * The table column <code>calc.specimen_measurement.specimen_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT specimen_measurement__fk_specimen_measurement_specimen
	 * FOREIGN KEY (specimen_id)
	 * REFERENCES calc.specimen (id)
	 * </pre></code>
	 */
	public java.lang.Integer getSpecimenId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.SPECIMEN_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord 
	 * SpecimenRecord}
	 */
	public void setSpecimenId(org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.SPECIMEN_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.SPECIMEN_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.SpecimenTable.SPECIMEN.ID));
		}
	}

	/**
	 * The table column <code>calc.specimen_measurement.specimen_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT specimen_measurement__fk_specimen_measurement_specimen
	 * FOREIGN KEY (specimen_id)
	 * REFERENCES calc.specimen (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord fetchSpecimenTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.SpecimenTable.SPECIMEN)
			.where(org.openforis.calc.persistence.jooq.tables.SpecimenTable.SPECIMEN.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.SPECIMEN_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.specimen_measurement.variable_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT specimen_measurement__fk_specimen_measurement_variable
	 * FOREIGN KEY (variable_id)
	 * REFERENCES calc.variable (id)
	 * </pre></code>
	 */
	public void setVariableId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.VARIABLE_ID, value);
	}

	/**
	 * The table column <code>calc.specimen_measurement.variable_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT specimen_measurement__fk_specimen_measurement_variable
	 * FOREIGN KEY (variable_id)
	 * REFERENCES calc.variable (id)
	 * </pre></code>
	 */
	public java.lang.Integer getVariableId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.VARIABLE_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.VariableRecord 
	 * VariableRecord}
	 */
	public void setVariableId(org.openforis.calc.persistence.jooq.tables.records.VariableRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.VARIABLE_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.VARIABLE_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE.ID));
		}
	}

	/**
	 * The table column <code>calc.specimen_measurement.variable_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT specimen_measurement__fk_specimen_measurement_variable
	 * FOREIGN KEY (variable_id)
	 * REFERENCES calc.variable (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.VariableRecord fetchVariableTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE)
			.where(org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.VARIABLE_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.specimen_measurement.value</code>
	 */
	public void setValue(java.lang.Double value) {
		setValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.VALUE, value);
	}

	/**
	 * The table column <code>calc.specimen_measurement.value</code>
	 */
	public java.lang.Double getValue() {
		return getValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.VALUE);
	}

	/**
	 * The table column <code>calc.specimen_measurement.computed</code>
	 */
	public void setComputed(java.lang.Boolean value) {
		setValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.COMPUTED, value);
	}

	/**
	 * The table column <code>calc.specimen_measurement.computed</code>
	 */
	public java.lang.Boolean getComputed() {
		return getValue(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT.COMPUTED);
	}

	/**
	 * Create a detached SpecimenMeasurementRecord
	 */
	public SpecimenMeasurementRecord() {
		super(org.openforis.calc.persistence.jooq.tables.SpecimenMeasurementTable.SPECIMEN_MEASUREMENT);
	}
}
