/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class TaxonVernacularNameRecord extends org.jooq.impl.UpdatableRecordImpl<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord> {

	private static final long serialVersionUID = -744157330;

	/**
	 * The table column <code>calc.taxon_vernacular_name.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.ID, value);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.ID);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.accepted_name_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT taxon_vernacular_name__fk_taxon_vernacular_name_accepted_usage
	 * FOREIGN KEY (accepted_name_id)
	 * REFERENCES calc.taxon (id)
	 * </pre></code>
	 */
	public void setAcceptedNameId(java.lang.Integer value) {
		setValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.ACCEPTED_NAME_ID, value);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.accepted_name_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT taxon_vernacular_name__fk_taxon_vernacular_name_accepted_usage
	 * FOREIGN KEY (accepted_name_id)
	 * REFERENCES calc.taxon (id)
	 * </pre></code>
	 */
	public java.lang.Integer getAcceptedNameId() {
		return getValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.ACCEPTED_NAME_ID);
	}

	/**
	 * Link this record to a given {@link org.openforis.calc.persistence.jooq.tables.records.TaxonRecord 
	 * TaxonRecord}
	 */
	public void setAcceptedNameId(org.openforis.calc.persistence.jooq.tables.records.TaxonRecord value) {
		if (value == null) {
			setValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.ACCEPTED_NAME_ID, null);
		}
		else {
			setValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.ACCEPTED_NAME_ID, value.getValue(org.openforis.calc.persistence.jooq.tables.TaxonTable.TAXON.ID));
		}
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.accepted_name_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT taxon_vernacular_name__fk_taxon_vernacular_name_accepted_usage
	 * FOREIGN KEY (accepted_name_id)
	 * REFERENCES calc.taxon (id)
	 * </pre></code>
	 */
	public org.openforis.calc.persistence.jooq.tables.records.TaxonRecord fetchTaxonTable() {
		return create()
			.selectFrom(org.openforis.calc.persistence.jooq.tables.TaxonTable.TAXON)
			.where(org.openforis.calc.persistence.jooq.tables.TaxonTable.TAXON.ID.equal(getValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.ACCEPTED_NAME_ID)))
			.fetchOne();
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.name</code>
	 */
	public void setName(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.NAME, value);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.name</code>
	 */
	public java.lang.String getName() {
		return getValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.NAME);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.language_code</code>
	 */
	public void setLanguageCode(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.LANGUAGE_CODE, value);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.language_code</code>
	 */
	public java.lang.String getLanguageCode() {
		return getValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.LANGUAGE_CODE);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.language_variant</code>
	 */
	public void setLanguageVariant(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.LANGUAGE_VARIANT, value);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.language_variant</code>
	 */
	public java.lang.String getLanguageVariant() {
		return getValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.LANGUAGE_VARIANT);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.qualifier</code>
	 */
	public void setQualifier(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.QUALIFIER, value);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.qualifier</code>
	 */
	public java.lang.String getQualifier() {
		return getValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.QUALIFIER);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.remarks</code>
	 */
	public void setRemarks(java.lang.String value) {
		setValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.REMARKS, value);
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.remarks</code>
	 */
	public java.lang.String getRemarks() {
		return getValue(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME.REMARKS);
	}

	/**
	 * Create a detached TaxonVernacularNameRecord
	 */
	public TaxonVernacularNameRecord() {
		super(org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME);
	}
}
