/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class AoiTable extends org.jooq.impl.UpdatableTableImpl<org.openforis.calc.persistence.jooq.tables.records.AoiRecord> {

	private static final long serialVersionUID = -1210043300;

	/**
	 * The singleton instance of calc.aoi
	 */
	public static final org.openforis.calc.persistence.jooq.tables.AoiTable AOI = new org.openforis.calc.persistence.jooq.tables.AoiTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.openforis.calc.persistence.jooq.tables.records.AoiRecord> getRecordType() {
		return org.openforis.calc.persistence.jooq.tables.records.AoiRecord.class;
	}

	/**
	 * The table column <code>calc.aoi.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.aoi.hierarchy_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT aoi__fk_aoi_hierarchy
	 * FOREIGN KEY (hierarchy_id)
	 * REFERENCES calc.aoi_hierarchy (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, java.lang.Integer> HIERARCHY_ID = createField("hierarchy_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.aoi.code</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, java.lang.String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.aoi.name</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.aoi.geometry</code>
	 * <p>
	 * The SQL type of this item (polygon) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, java.lang.Object> GEOMETRY = createField("geometry", org.jooq.util.postgres.PostgresDataType.getDefaultDataType("polygon"), this);

	/**
	 * The table column <code>calc.aoi.area</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, java.math.BigDecimal> AREA = createField("area", org.jooq.impl.SQLDataType.NUMERIC, this);

	/**
	 * The table column <code>calc.aoi.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT aoi__fk_aoi_parent
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.aoi (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, java.lang.Integer> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.aoi.level</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, java.lang.Integer> LEVEL = createField("level", org.jooq.impl.SQLDataType.INTEGER, this);

	public AoiTable() {
		super("aoi", org.openforis.calc.persistence.jooq.CalcTable.CALC);
	}

	public AoiTable(java.lang.String alias) {
		super(alias, org.openforis.calc.persistence.jooq.CalcTable.CALC, org.openforis.calc.persistence.jooq.tables.AoiTable.AOI);
	}

	@Override
	public org.jooq.Identity<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, java.lang.Integer> getIdentity() {
		return org.openforis.calc.persistence.jooq.Keys.IDENTITY_AOI;
	}

	@Override
	public org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.AoiRecord> getMainKey() {
		return org.openforis.calc.persistence.jooq.Keys.AOI_PKEY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.AoiRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.AoiRecord>>asList(org.openforis.calc.persistence.jooq.Keys.AOI_PKEY);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.AoiRecord, ?>>asList(org.openforis.calc.persistence.jooq.Keys.AOI__FK_AOI_HIERARCHY, org.openforis.calc.persistence.jooq.Keys.AOI__FK_AOI_PARENT);
	}

	@Override
	public org.openforis.calc.persistence.jooq.tables.AoiTable as(java.lang.String alias) {
		return new org.openforis.calc.persistence.jooq.tables.AoiTable(alias);
	}
}
