/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class ClusterTable extends org.jooq.impl.UpdatableTableImpl<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord> {

	private static final long serialVersionUID = -2118635589;

	/**
	 * The singleton instance of calc.cluster
	 */
	public static final org.openforis.calc.persistence.jooq.tables.ClusterTable CLUSTER = new org.openforis.calc.persistence.jooq.tables.ClusterTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord> getRecordType() {
		return org.openforis.calc.persistence.jooq.tables.records.ClusterRecord.class;
	}

	/**
	 * The table column <code>calc.cluster.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.cluster.survey_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT cluster__fk_cluster_survey
	 * FOREIGN KEY (survey_id)
	 * REFERENCES calc.survey (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord, java.lang.Integer> SURVEY_ID = createField("survey_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.cluster.no</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord, java.lang.Integer> NO = createField("no", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.cluster.code</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord, java.lang.String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.cluster.x_index</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord, java.lang.Integer> X_INDEX = createField("x_index", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.cluster.y_index</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord, java.lang.Integer> Y_INDEX = createField("y_index", org.jooq.impl.SQLDataType.INTEGER, this);

	public ClusterTable() {
		super("cluster", org.openforis.calc.persistence.jooq.CalcTable.CALC);
	}

	public ClusterTable(java.lang.String alias) {
		super(alias, org.openforis.calc.persistence.jooq.CalcTable.CALC, org.openforis.calc.persistence.jooq.tables.ClusterTable.CLUSTER);
	}

	@Override
	public org.jooq.Identity<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord, java.lang.Integer> getIdentity() {
		return org.openforis.calc.persistence.jooq.Keys.IDENTITY_CLUSTER;
	}

	@Override
	public org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord> getMainKey() {
		return org.openforis.calc.persistence.jooq.Keys.CLUSTER_PKEY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord>>asList(org.openforis.calc.persistence.jooq.Keys.CLUSTER_PKEY, org.openforis.calc.persistence.jooq.Keys.UK_CLUSTER_CODE);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.ClusterRecord, ?>>asList(org.openforis.calc.persistence.jooq.Keys.CLUSTER__FK_CLUSTER_SURVEY);
	}

	@Override
	public org.openforis.calc.persistence.jooq.tables.ClusterTable as(java.lang.String alias) {
		return new org.openforis.calc.persistence.jooq.tables.ClusterTable(alias);
	}
}
