/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class PlotCategoryTable extends org.jooq.impl.UpdatableTableImpl<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord> {

	private static final long serialVersionUID = -1346822703;

	/**
	 * The singleton instance of calc.plot_category
	 */
	public static final org.openforis.calc.persistence.jooq.tables.PlotCategoryTable PLOT_CATEGORY = new org.openforis.calc.persistence.jooq.tables.PlotCategoryTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord> getRecordType() {
		return org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord.class;
	}

	/**
	 * The table column <code>calc.plot_category.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_category.plot_survey_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_category__fk_plot_category_survey
	 * FOREIGN KEY (plot_survey_id)
	 * REFERENCES calc.plot_survey (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord, java.lang.Integer> PLOT_SURVEY_ID = createField("plot_survey_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_category.category_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT plot_category__fk_plot_category_category
	 * FOREIGN KEY (category_id)
	 * REFERENCES calc.category (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord, java.lang.Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_category.computed</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord, java.lang.Boolean> COMPUTED = createField("computed", org.jooq.impl.SQLDataType.BOOLEAN, this);

	public PlotCategoryTable() {
		super("plot_category", org.openforis.calc.persistence.jooq.CalcTable.CALC);
	}

	public PlotCategoryTable(java.lang.String alias) {
		super(alias, org.openforis.calc.persistence.jooq.CalcTable.CALC, org.openforis.calc.persistence.jooq.tables.PlotCategoryTable.PLOT_CATEGORY);
	}

	@Override
	public org.jooq.Identity<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord, java.lang.Integer> getIdentity() {
		return org.openforis.calc.persistence.jooq.Keys.IDENTITY_PLOT_CATEGORY;
	}

	@Override
	public org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord> getMainKey() {
		return org.openforis.calc.persistence.jooq.Keys.PLOT_CATEGORY_PKEY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord>>asList(org.openforis.calc.persistence.jooq.Keys.PLOT_CATEGORY_PKEY);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.PlotCategoryRecord, ?>>asList(org.openforis.calc.persistence.jooq.Keys.PLOT_CATEGORY__FK_PLOT_CATEGORY_SURVEY, org.openforis.calc.persistence.jooq.Keys.PLOT_CATEGORY__FK_PLOT_CATEGORY_CATEGORY);
	}

	@Override
	public org.openforis.calc.persistence.jooq.tables.PlotCategoryTable as(java.lang.String alias) {
		return new org.openforis.calc.persistence.jooq.tables.PlotCategoryTable(alias);
	}
}
