/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class PlotMeasurementViewTable extends org.jooq.impl.TableImpl<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord> {

	private static final long serialVersionUID = 794618645;

	/**
	 * The singleton instance of calc.plot_measurement_view
	 */
	public static final org.openforis.calc.persistence.jooq.tables.PlotMeasurementViewTable PLOT_MEASUREMENT_VIEW = new org.openforis.calc.persistence.jooq.tables.PlotMeasurementViewTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord> getRecordType() {
		return org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord.class;
	}

	/**
	 * The table column <code>calc.plot_measurement_view.survey_id</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> SURVEY_ID = createField("survey_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.stratum_id</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> STRATUM_ID = createField("stratum_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.stratum_no</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> STRATUM_NO = createField("stratum_no", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.stratum_code</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.String> STRATUM_CODE = createField("stratum_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.plot_measurement_view.cluster_id</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> CLUSTER_ID = createField("cluster_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.cluster_no</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> CLUSTER_NO = createField("cluster_no", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.cluster_code</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.String> CLUSTER_CODE = createField("cluster_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.plot_measurement_view.cluster_x</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> CLUSTER_X = createField("cluster_x", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.cluster_y</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> CLUSTER_Y = createField("cluster_y", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.plot_id</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> PLOT_ID = createField("plot_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.plot_survey_parent_id</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> PLOT_SURVEY_PARENT_ID = createField("plot_survey_parent_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.plot_no</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> PLOT_NO = createField("plot_no", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.plot_code</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.String> PLOT_CODE = createField("plot_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.plot_measurement_view.plot_survey_id</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> PLOT_SURVEY_ID = createField("plot_survey_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.plot_section</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> PLOT_SECTION = createField("plot_section", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.survey_type</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.String> SURVEY_TYPE = createField("survey_type", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * The table column <code>calc.plot_measurement_view.obs_unit_id</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> OBS_UNIT_ID = createField("obs_unit_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.obs_unit_name</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.String> OBS_UNIT_NAME = createField("obs_unit_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.plot_measurement_view.step</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Integer> STEP = createField("step", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.plot_measurement_view.variable_name</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.String> VARIABLE_NAME = createField("variable_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.plot_measurement_view.value</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Double> VALUE = createField("value", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The table column <code>calc.plot_measurement_view.computed</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.PlotMeasurementViewRecord, java.lang.Boolean> COMPUTED = createField("computed", org.jooq.impl.SQLDataType.BOOLEAN, this);

	public PlotMeasurementViewTable() {
		super("plot_measurement_view", org.openforis.calc.persistence.jooq.CalcTable.CALC);
	}

	public PlotMeasurementViewTable(java.lang.String alias) {
		super(alias, org.openforis.calc.persistence.jooq.CalcTable.CALC, org.openforis.calc.persistence.jooq.tables.PlotMeasurementViewTable.PLOT_MEASUREMENT_VIEW);
	}

	@Override
	public org.openforis.calc.persistence.jooq.tables.PlotMeasurementViewTable as(java.lang.String alias) {
		return new org.openforis.calc.persistence.jooq.tables.PlotMeasurementViewTable(alias);
	}
}
