/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class SpecimenTable extends org.jooq.impl.UpdatableTableImpl<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord> {

	private static final long serialVersionUID = -2041884111;

	/**
	 * The singleton instance of calc.specimen
	 */
	public static final org.openforis.calc.persistence.jooq.tables.SpecimenTable SPECIMEN = new org.openforis.calc.persistence.jooq.tables.SpecimenTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord> getRecordType() {
		return org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord.class;
	}

	/**
	 * The table column <code>calc.specimen.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.specimen.plot_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT specimen__fk_specimen_plot
	 * FOREIGN KEY (plot_id)
	 * REFERENCES calc.plot_survey (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord, java.lang.Integer> PLOT_ID = createField("plot_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.specimen.obs_unit_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT specimen__fk_specimen_obs_unit
	 * FOREIGN KEY (obs_unit_id)
	 * REFERENCES calc.observation_unit (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord, java.lang.Integer> OBS_UNIT_ID = createField("obs_unit_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.specimen.taxon_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT specimen__fk_specimen_taxon
	 * FOREIGN KEY (taxon_id)
	 * REFERENCES calc.taxon (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord, java.lang.Integer> TAXON_ID = createField("taxon_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.specimen.survey_date</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord, java.sql.Date> SURVEY_DATE = createField("survey_date", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The table column <code>calc.specimen.source_id</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord, java.lang.Integer> SOURCE_ID = createField("source_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.specimen.parent_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT specimen__fk_specimen_parent
	 * FOREIGN KEY (parent_id)
	 * REFERENCES calc.specimen (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord, java.lang.Integer> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.INTEGER, this);

	public SpecimenTable() {
		super("specimen", org.openforis.calc.persistence.jooq.CalcTable.CALC);
	}

	public SpecimenTable(java.lang.String alias) {
		super(alias, org.openforis.calc.persistence.jooq.CalcTable.CALC, org.openforis.calc.persistence.jooq.tables.SpecimenTable.SPECIMEN);
	}

	@Override
	public org.jooq.Identity<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord, java.lang.Integer> getIdentity() {
		return org.openforis.calc.persistence.jooq.Keys.IDENTITY_SPECIMEN;
	}

	@Override
	public org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord> getMainKey() {
		return org.openforis.calc.persistence.jooq.Keys.SPECIMEN_PKEY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord>>asList(org.openforis.calc.persistence.jooq.Keys.SPECIMEN_PKEY);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.SpecimenRecord, ?>>asList(org.openforis.calc.persistence.jooq.Keys.SPECIMEN__FK_SPECIMEN_PLOT, org.openforis.calc.persistence.jooq.Keys.SPECIMEN__FK_SPECIMEN_OBS_UNIT, org.openforis.calc.persistence.jooq.Keys.SPECIMEN__FK_SPECIMEN_TAXON, org.openforis.calc.persistence.jooq.Keys.SPECIMEN__FK_SPECIMEN_PARENT);
	}

	@Override
	public org.openforis.calc.persistence.jooq.tables.SpecimenTable as(java.lang.String alias) {
		return new org.openforis.calc.persistence.jooq.tables.SpecimenTable(alias);
	}
}
