/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class StratumTable extends org.jooq.impl.UpdatableTableImpl<org.openforis.calc.persistence.jooq.tables.records.StratumRecord> {

	private static final long serialVersionUID = 1817751337;

	/**
	 * The singleton instance of calc.stratum
	 */
	public static final org.openforis.calc.persistence.jooq.tables.StratumTable STRATUM = new org.openforis.calc.persistence.jooq.tables.StratumTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.openforis.calc.persistence.jooq.tables.records.StratumRecord> getRecordType() {
		return org.openforis.calc.persistence.jooq.tables.records.StratumRecord.class;
	}

	/**
	 * The table column <code>calc.stratum.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.StratumRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.stratum.survey_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT stratum__fk_stratum_survey
	 * FOREIGN KEY (survey_id)
	 * REFERENCES calc.survey (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.StratumRecord, java.lang.Integer> SURVEY_ID = createField("survey_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.stratum.no</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.StratumRecord, java.lang.Integer> NO = createField("no", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.stratum.code</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.StratumRecord, java.lang.String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.stratum.description</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.StratumRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR, this);

	public StratumTable() {
		super("stratum", org.openforis.calc.persistence.jooq.CalcTable.CALC);
	}

	public StratumTable(java.lang.String alias) {
		super(alias, org.openforis.calc.persistence.jooq.CalcTable.CALC, org.openforis.calc.persistence.jooq.tables.StratumTable.STRATUM);
	}

	@Override
	public org.jooq.Identity<org.openforis.calc.persistence.jooq.tables.records.StratumRecord, java.lang.Integer> getIdentity() {
		return org.openforis.calc.persistence.jooq.Keys.IDENTITY_STRATUM;
	}

	@Override
	public org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.StratumRecord> getMainKey() {
		return org.openforis.calc.persistence.jooq.Keys.STRATUM_PKEY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.StratumRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.StratumRecord>>asList(org.openforis.calc.persistence.jooq.Keys.STRATUM_PKEY, org.openforis.calc.persistence.jooq.Keys.UK_STRATUM_CODE);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.StratumRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.StratumRecord, ?>>asList(org.openforis.calc.persistence.jooq.Keys.STRATUM__FK_STRATUM_SURVEY);
	}

	@Override
	public org.openforis.calc.persistence.jooq.tables.StratumTable as(java.lang.String alias) {
		return new org.openforis.calc.persistence.jooq.tables.StratumTable(alias);
	}
}
