/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class SurveyTable extends org.jooq.impl.UpdatableTableImpl<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord> {

	private static final long serialVersionUID = 653245786;

	/**
	 * The singleton instance of calc.survey
	 */
	public static final org.openforis.calc.persistence.jooq.tables.SurveyTable SURVEY = new org.openforis.calc.persistence.jooq.tables.SurveyTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord> getRecordType() {
		return org.openforis.calc.persistence.jooq.tables.records.SurveyRecord.class;
	}

	/**
	 * The table column <code>calc.survey.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.survey.uri</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord, java.lang.String> URI = createField("uri", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.survey.default_label</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord, java.lang.String> DEFAULT_LABEL = createField("default_label", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.survey.description</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.survey.cycle</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord, java.lang.String> CYCLE = createField("cycle", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.survey.from_date</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord, java.sql.Date> FROM_DATE = createField("from_date", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The table column <code>calc.survey.to_date</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord, java.sql.Date> TO_DATE = createField("to_date", org.jooq.impl.SQLDataType.DATE, this);

	public SurveyTable() {
		super("survey", org.openforis.calc.persistence.jooq.CalcTable.CALC);
	}

	public SurveyTable(java.lang.String alias) {
		super(alias, org.openforis.calc.persistence.jooq.CalcTable.CALC, org.openforis.calc.persistence.jooq.tables.SurveyTable.SURVEY);
	}

	@Override
	public org.jooq.Identity<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord, java.lang.Integer> getIdentity() {
		return org.openforis.calc.persistence.jooq.Keys.IDENTITY_SURVEY;
	}

	@Override
	public org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord> getMainKey() {
		return org.openforis.calc.persistence.jooq.Keys.SURVEY_PKEY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.SurveyRecord>>asList(org.openforis.calc.persistence.jooq.Keys.SURVEY_PKEY, org.openforis.calc.persistence.jooq.Keys.UK_SURVEY_URI);
	}

	@Override
	public org.openforis.calc.persistence.jooq.tables.SurveyTable as(java.lang.String alias) {
		return new org.openforis.calc.persistence.jooq.tables.SurveyTable(alias);
	}
}
