/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class TaxonomicChecklistTable extends org.jooq.impl.UpdatableTableImpl<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord> {

	private static final long serialVersionUID = 1585759227;

	/**
	 * The singleton instance of calc.taxonomic_checklist
	 */
	public static final org.openforis.calc.persistence.jooq.tables.TaxonomicChecklistTable TAXONOMIC_CHECKLIST = new org.openforis.calc.persistence.jooq.tables.TaxonomicChecklistTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord> getRecordType() {
		return org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord.class;
	}

	/**
	 * The table column <code>calc.taxonomic_checklist.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.taxonomic_checklist.survey_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT taxonomic_checklist__fk_taxonomic_checklist_survey
	 * FOREIGN KEY (survey_id)
	 * REFERENCES calc.survey (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord, java.lang.Integer> SURVEY_ID = createField("survey_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.taxonomic_checklist.name</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TaxonomicChecklistTable() {
		super("taxonomic_checklist", org.openforis.calc.persistence.jooq.CalcTable.CALC);
	}

	public TaxonomicChecklistTable(java.lang.String alias) {
		super(alias, org.openforis.calc.persistence.jooq.CalcTable.CALC, org.openforis.calc.persistence.jooq.tables.TaxonomicChecklistTable.TAXONOMIC_CHECKLIST);
	}

	@Override
	public org.jooq.Identity<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord, java.lang.Integer> getIdentity() {
		return org.openforis.calc.persistence.jooq.Keys.IDENTITY_TAXONOMIC_CHECKLIST;
	}

	@Override
	public org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord> getMainKey() {
		return org.openforis.calc.persistence.jooq.Keys.TAXONOMIC_CHECKLIST_PKEY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord>>asList(org.openforis.calc.persistence.jooq.Keys.TAXONOMIC_CHECKLIST_PKEY);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.TaxonomicChecklistRecord, ?>>asList(org.openforis.calc.persistence.jooq.Keys.TAXONOMIC_CHECKLIST__FK_TAXONOMIC_CHECKLIST_SURVEY);
	}

	@Override
	public org.openforis.calc.persistence.jooq.tables.TaxonomicChecklistTable as(java.lang.String alias) {
		return new org.openforis.calc.persistence.jooq.tables.TaxonomicChecklistTable(alias);
	}
}
