/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class TaxonVernacularNameTable extends org.jooq.impl.UpdatableTableImpl<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord> {

	private static final long serialVersionUID = 794093258;

	/**
	 * The singleton instance of calc.taxon_vernacular_name
	 */
	public static final org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable TAXON_VERNACULAR_NAME = new org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord> getRecordType() {
		return org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord.class;
	}

	/**
	 * The table column <code>calc.taxon_vernacular_name.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.taxon_vernacular_name.accepted_name_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT taxon_vernacular_name__fk_taxon_vernacular_name_accepted_usage
	 * FOREIGN KEY (accepted_name_id)
	 * REFERENCES calc.taxon (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord, java.lang.Integer> ACCEPTED_NAME_ID = createField("accepted_name_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.taxon_vernacular_name.name</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.taxon_vernacular_name.language_code</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord, java.lang.String> LANGUAGE_CODE = createField("language_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.taxon_vernacular_name.language_variant</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord, java.lang.String> LANGUAGE_VARIANT = createField("language_variant", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.taxon_vernacular_name.qualifier</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord, java.lang.String> QUALIFIER = createField("qualifier", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.taxon_vernacular_name.remarks</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord, java.lang.String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TaxonVernacularNameTable() {
		super("taxon_vernacular_name", org.openforis.calc.persistence.jooq.CalcTable.CALC);
	}

	public TaxonVernacularNameTable(java.lang.String alias) {
		super(alias, org.openforis.calc.persistence.jooq.CalcTable.CALC, org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable.TAXON_VERNACULAR_NAME);
	}

	@Override
	public org.jooq.Identity<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord, java.lang.Integer> getIdentity() {
		return org.openforis.calc.persistence.jooq.Keys.IDENTITY_TAXON_VERNACULAR_NAME;
	}

	@Override
	public org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord> getMainKey() {
		return org.openforis.calc.persistence.jooq.Keys.TAXON_VERNACULAR_NAME_PKEY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord>>asList(org.openforis.calc.persistence.jooq.Keys.TAXON_VERNACULAR_NAME_PKEY);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.TaxonVernacularNameRecord, ?>>asList(org.openforis.calc.persistence.jooq.Keys.TAXON_VERNACULAR_NAME__FK_TAXON_VERNACULAR_NAME_ACCEPTED_USAGE);
	}

	@Override
	public org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable as(java.lang.String alias) {
		return new org.openforis.calc.persistence.jooq.tables.TaxonVernacularNameTable(alias);
	}
}
