/**
 * This class is generated by jOOQ
 */
package org.openforis.calc.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.0"},
                            comments = "This class is generated by jOOQ")
public class VariableTable extends org.jooq.impl.UpdatableTableImpl<org.openforis.calc.persistence.jooq.tables.records.VariableRecord> {

	private static final long serialVersionUID = -1612367210;

	/**
	 * The singleton instance of calc.variable
	 */
	public static final org.openforis.calc.persistence.jooq.tables.VariableTable VARIABLE = new org.openforis.calc.persistence.jooq.tables.VariableTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.openforis.calc.persistence.jooq.tables.records.VariableRecord> getRecordType() {
		return org.openforis.calc.persistence.jooq.tables.records.VariableRecord.class;
	}

	/**
	 * The table column <code>calc.variable.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.VariableRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.variable.obs_unit_id</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT variable__fk_variable_obs_unit
	 * FOREIGN KEY (obs_unit_id)
	 * REFERENCES calc.observation_unit (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.VariableRecord, java.lang.Integer> OBS_UNIT_ID = createField("obs_unit_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.variable.type</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.VariableRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.variable.name</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.VariableRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>calc.variable.order</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.VariableRecord, java.lang.Integer> ORDER = createField("order", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.variable.source_id</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.VariableRecord, java.lang.Integer> SOURCE_ID = createField("source_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>calc.variable.default_label</code>
	 */
	public final org.jooq.TableField<org.openforis.calc.persistence.jooq.tables.records.VariableRecord, java.lang.String> DEFAULT_LABEL = createField("default_label", org.jooq.impl.SQLDataType.VARCHAR, this);

	public VariableTable() {
		super("variable", org.openforis.calc.persistence.jooq.CalcTable.CALC);
	}

	public VariableTable(java.lang.String alias) {
		super(alias, org.openforis.calc.persistence.jooq.CalcTable.CALC, org.openforis.calc.persistence.jooq.tables.VariableTable.VARIABLE);
	}

	@Override
	public org.jooq.Identity<org.openforis.calc.persistence.jooq.tables.records.VariableRecord, java.lang.Integer> getIdentity() {
		return org.openforis.calc.persistence.jooq.Keys.IDENTITY_VARIABLE;
	}

	@Override
	public org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.VariableRecord> getMainKey() {
		return org.openforis.calc.persistence.jooq.Keys.VARIABLE_PKEY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.VariableRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.openforis.calc.persistence.jooq.tables.records.VariableRecord>>asList(org.openforis.calc.persistence.jooq.Keys.VARIABLE_PKEY, org.openforis.calc.persistence.jooq.Keys.UK_VARIABLE_NAME);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.VariableRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.openforis.calc.persistence.jooq.tables.records.VariableRecord, ?>>asList(org.openforis.calc.persistence.jooq.Keys.VARIABLE__FK_VARIABLE_OBS_UNIT);
	}

	@Override
	public org.openforis.calc.persistence.jooq.tables.VariableTable as(java.lang.String alias) {
		return new org.openforis.calc.persistence.jooq.tables.VariableTable(alias);
	}
}
