//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.01 at 03:55:36 PM CET 
//


package org.openforis.calc.olap;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import org.openforis.calc.model.VariableMetadata;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hierarchy", propOrder = {
    "annotations",
    "table",
    "view",
    "join",
    "inlineTable",
    "level",
    "memberReaderParameter"
})
public class Hierarchy {

    @XmlElement(name = "Annotations")
    protected Annotations annotations;
    @XmlElement(name = "Table")
    protected Table table;
    @XmlElement(name = "View")
    protected View view;
    @XmlElement(name = "Join")
    protected Hierarchy.Join join;
    @XmlElement(name = "InlineTable")
    protected Hierarchy.InlineTable inlineTable;
    @XmlElement(name = "Level", required = true)
    protected List<Hierarchy.Level> level;
    @XmlElement(name = "MemberReaderParameter")
    protected List<Hierarchy.MemberReaderParameter> memberReaderParameter;
    @XmlAttribute
    protected String name;
    @XmlAttribute(required = true)
    protected boolean hasAll;
    @XmlAttribute
    protected String allMemberName;
    @XmlAttribute
    protected String allMemberCaption;
    @XmlAttribute
    protected String allLevelName;
    @XmlAttribute
    protected String primaryKey;
    @XmlAttribute
    protected String primaryKeyTable;
    @XmlAttribute
    protected String defaultMember;
    @XmlAttribute
    protected String memberReaderClass;
    @XmlAttribute
    protected String caption;
    @XmlAttribute
    protected String description;
    @XmlAttribute
    protected String uniqueKeyLevelName;
    @XmlAttribute
    protected Boolean visible;
    
    
    public Hierarchy() {
	}

	public Hierarchy(VariableMetadata variableMetadata) {
		setVisible(true);
		setHasAll(true);
		setName( Schema.getMdxName(variableMetadata.getVariableName()) );
		setTable( new Table(variableMetadata) );
		getLevels().add( new Level(variableMetadata) );
	}

	/**
     * Gets the value of the annotations property.
     * 
     * @return
     *     possible object is
     *     {@link Annotations }
     *     
     */
    public Annotations getAnnotations() {
        return annotations;
    }

    /**
     * Sets the value of the annotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotations }
     *     
     */
    public void setAnnotations(Annotations value) {
        this.annotations = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link Table }
     *     
     */
    public Table getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link Table }
     *     
     */
    public void setTable(Table value) {
        this.table = value;
    }

    /**
     * Gets the value of the view property.
     * 
     * @return
     *     possible object is
     *     {@link View }
     *     
     */
    public View getView() {
        return view;
    }

    /**
     * Sets the value of the view property.
     * 
     * @param value
     *     allowed object is
     *     {@link View }
     *     
     */
    public void setView(View value) {
        this.view = value;
    }

    /**
     * Gets the value of the join property.
     * 
     * @return
     *     possible object is
     *     {@link Hierarchy.Join }
     *     
     */
    public Hierarchy.Join getJoin() {
        return join;
    }

    /**
     * Sets the value of the join property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hierarchy.Join }
     *     
     */
    public void setJoin(Hierarchy.Join value) {
        this.join = value;
    }

    /**
     * Gets the value of the inlineTable property.
     * 
     * @return
     *     possible object is
     *     {@link Hierarchy.InlineTable }
     *     
     */
    public Hierarchy.InlineTable getInlineTable() {
        return inlineTable;
    }

    /**
     * Sets the value of the inlineTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hierarchy.InlineTable }
     *     
     */
    public void setInlineTable(Hierarchy.InlineTable value) {
        this.inlineTable = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the level property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hierarchy.Level }
     * 
     * 
     */
    public List<Hierarchy.Level> getLevels() {
        if (level == null) {
            level = new ArrayList<Hierarchy.Level>();
        }
        return this.level;
    }

    /**
     * Gets the value of the memberReaderParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memberReaderParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemberReaderParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hierarchy.MemberReaderParameter }
     * 
     * 
     */
    public List<Hierarchy.MemberReaderParameter> getMemberReaderParameter() {
        if (memberReaderParameter == null) {
            memberReaderParameter = new ArrayList<Hierarchy.MemberReaderParameter>();
        }
        return this.memberReaderParameter;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the hasAll property.
     * 
     */
    public boolean isHasAll() {
        return hasAll;
    }

    /**
     * Sets the value of the hasAll property.
     * 
     */
    public void setHasAll(boolean value) {
        this.hasAll = value;
    }

    /**
     * Gets the value of the allMemberName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllMemberName() {
        return allMemberName;
    }

    /**
     * Sets the value of the allMemberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllMemberName(String value) {
        this.allMemberName = value;
    }

    /**
     * Gets the value of the allMemberCaption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllMemberCaption() {
        return allMemberCaption;
    }

    /**
     * Sets the value of the allMemberCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllMemberCaption(String value) {
        this.allMemberCaption = value;
    }

    /**
     * Gets the value of the allLevelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllLevelName() {
        return allLevelName;
    }

    /**
     * Sets the value of the allLevelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllLevelName(String value) {
        this.allLevelName = value;
    }

    /**
     * Gets the value of the primaryKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryKey() {
        return primaryKey;
    }

    /**
     * Sets the value of the primaryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryKey(String value) {
        this.primaryKey = value;
    }

    /**
     * Gets the value of the primaryKeyTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryKeyTable() {
        return primaryKeyTable;
    }

    /**
     * Sets the value of the primaryKeyTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryKeyTable(String value) {
        this.primaryKeyTable = value;
    }

    /**
     * Gets the value of the defaultMember property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultMember() {
        return defaultMember;
    }

    /**
     * Sets the value of the defaultMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultMember(String value) {
        this.defaultMember = value;
    }

    /**
     * Gets the value of the memberReaderClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberReaderClass() {
        return memberReaderClass;
    }

    /**
     * Sets the value of the memberReaderClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberReaderClass(String value) {
        this.memberReaderClass = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the uniqueKeyLevelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueKeyLevelName() {
        return uniqueKeyLevelName;
    }

    /**
     * Sets the value of the uniqueKeyLevelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueKeyLevelName(String value) {
        this.uniqueKeyLevelName = value;
    }

    public Boolean getVisible() {
		return visible;
	}
    
    public void setVisible(Boolean visible) {
		this.visible = visible;
	}

  
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "columnDefs",
        "rows"
    })
    public static class InlineTable {

        @XmlElement(name = "ColumnDefs", required = true)
        protected Hierarchy.InlineTable.ColumnDefs columnDefs;
        @XmlElement(name = "Rows", required = true)
        protected Hierarchy.InlineTable.Rows rows;

        /**
         * Gets the value of the columnDefs property.
         * 
         * @return
         *     possible object is
         *     {@link Hierarchy.InlineTable.ColumnDefs }
         *     
         */
        public Hierarchy.InlineTable.ColumnDefs getColumnDefs() {
            return columnDefs;
        }

        /**
         * Sets the value of the columnDefs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Hierarchy.InlineTable.ColumnDefs }
         *     
         */
        public void setColumnDefs(Hierarchy.InlineTable.ColumnDefs value) {
            this.columnDefs = value;
        }

        /**
         * Gets the value of the rows property.
         * 
         * @return
         *     possible object is
         *     {@link Hierarchy.InlineTable.Rows }
         *     
         */
        public Hierarchy.InlineTable.Rows getRows() {
            return rows;
        }

        /**
         * Sets the value of the rows property.
         * 
         * @param value
         *     allowed object is
         *     {@link Hierarchy.InlineTable.Rows }
         *     
         */
        public void setRows(Hierarchy.InlineTable.Rows value) {
            this.rows = value;
        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "columnDef"
        })
        public static class ColumnDefs {

            @XmlElement(name = "ColumnDef", required = true)
            protected List<Hierarchy.InlineTable.ColumnDefs.ColumnDef> columnDef;

            /**
             * Gets the value of the columnDef property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the columnDef property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getColumnDef().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Hierarchy.InlineTable.ColumnDefs.ColumnDef }
             * 
             * 
             */
            public List<Hierarchy.InlineTable.ColumnDefs.ColumnDef> getColumnDef() {
                if (columnDef == null) {
                    columnDef = new ArrayList<Hierarchy.InlineTable.ColumnDefs.ColumnDef>();
                }
                return this.columnDef;
            }


           
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ColumnDef {

                @XmlAttribute
                protected String name;
                @XmlAttribute
                protected String type;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }

        }


        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "row"
        })
        public static class Rows {

            @XmlElement(name = "Row", required = true)
            protected List<Hierarchy.InlineTable.Rows.Row> row;

            /**
             * Gets the value of the row property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the row property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRow().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Hierarchy.InlineTable.Rows.Row }
             * 
             * 
             */
            public List<Hierarchy.InlineTable.Rows.Row> getRow() {
                if (row == null) {
                    row = new ArrayList<Hierarchy.InlineTable.Rows.Row>();
                }
                return this.row;
            }


        
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Row {

                @XmlElement(name = "Value", required = true)
                protected List<Hierarchy.InlineTable.Rows.Row.Value> value;

                /**
                 * Gets the value of the value property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the value property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getValue().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Hierarchy.InlineTable.Rows.Row.Value }
                 * 
                 * 
                 */
                public List<Hierarchy.InlineTable.Rows.Row.Value> getValue() {
                    if (value == null) {
                        value = new ArrayList<Hierarchy.InlineTable.Rows.Row.Value>();
                    }
                    return this.value;
                }


                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "content"
                })
                public static class Value {

                    @XmlValue
                    protected String content;
                    @XmlAttribute
                    protected String column;

                    /**
                     * Gets the value of the content property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getContent() {
                        return content;
                    }

                    /**
                     * Sets the value of the content property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setContent(String value) {
                        this.content = value;
                    }

                    /**
                     * Gets the value of the column property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getColumn() {
                        return column;
                    }

                    /**
                     * Sets the value of the column property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setColumn(String value) {
                        this.column = value;
                    }

                }

            }

        }

    }
   
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relation"
    })
    public static class Join {

        @XmlElements({
            @XmlElement(name = "Join", type = Hierarchy.Join.class),
            @XmlElement(name = "View", type = View.class),
            @XmlElement(name = "InlineTable", type = Hierarchy.InlineTable.class),
            @XmlElement(name = "Table", type = Table.class)
        })
        protected List<Object> relation;
        @XmlAttribute
        protected String leftAlias;
        @XmlAttribute
        protected String leftKey;
        @XmlAttribute
        protected String rightAlias;
        @XmlAttribute
        protected String rightKey;

        /**
         * Gets the value of the relation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Hierarchy.Join }
         * {@link View }
         * {@link Hierarchy.InlineTable }
         * {@link Table }
         * 
         * 
         */
        public List<Object> getRelation() {
            if (relation == null) {
                relation = new ArrayList<Object>();
            }
            return this.relation;
        }

        /**
         * Gets the value of the leftAlias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLeftAlias() {
            return leftAlias;
        }

        /**
         * Sets the value of the leftAlias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLeftAlias(String value) {
            this.leftAlias = value;
        }

        /**
         * Gets the value of the leftKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLeftKey() {
            return leftKey;
        }

        /**
         * Sets the value of the leftKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLeftKey(String value) {
            this.leftKey = value;
        }

        /**
         * Gets the value of the rightAlias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRightAlias() {
            return rightAlias;
        }

        /**
         * Sets the value of the rightAlias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRightAlias(String value) {
            this.rightAlias = value;
        }

        /**
         * Gets the value of the rightKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRightKey() {
            return rightKey;
        }

        /**
         * Sets the value of the rightKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRightKey(String value) {
            this.rightKey = value;
        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "annotations",
        "keyExpression",
        "nameExpression",
        "captionExpression",
        "ordinalExpression",
        "parentExpression",
        "closure",
        "property"
    })
    public static class Level {

        @XmlElement(name = "Annotations")
        protected Annotations annotations;
        @XmlElement(name = "KeyExpression")
        protected ExpressionView keyExpression;
        @XmlElement(name = "NameExpression")
        protected ExpressionView nameExpression;
        @XmlElement(name = "CaptionExpression")
        protected ExpressionView captionExpression;
        @XmlElement(name = "OrdinalExpression")
        protected ExpressionView ordinalExpression;
        @XmlElement(name = "ParentExpression")
        protected ExpressionView parentExpression;
        @XmlElement(name = "Closure")
        protected Hierarchy.Level.Closure closure;
        @XmlElement(name = "Property")
        protected List<Hierarchy.Level.Property> property;
        @XmlAttribute
        protected BigInteger approxRowCount;
        @XmlAttribute(required = true)
        protected String name;
        @XmlAttribute
        protected String table;
        @XmlAttribute
        protected String column;
        @XmlAttribute
        protected String nameColumn;
        @XmlAttribute
        protected String ordinalColumn;
        @XmlAttribute
        protected String parentColumn;
        @XmlAttribute
        protected String nullParentValue;
        @XmlAttribute
        protected String type;
        @XmlAttribute
        protected Boolean uniqueMembers;
        @XmlAttribute
        protected String levelType;
        @XmlAttribute
        protected String hideMemberIf;
        @XmlAttribute
        protected String formatter;
        @XmlAttribute
        protected String caption;
        @XmlAttribute
        protected String description;
        @XmlAttribute
        protected String captionColumn;
        @XmlAttribute
        protected Boolean visible;
        
        public Level() {
		}

		public Level(VariableMetadata variableMetadata) {
			setName( Schema.getMdxName(variableMetadata.getVariableName() ));
			setVisible( true );
			setTable( variableMetadata.getVariableName() );
			setColumn("category_id");
			setNameColumn("category_label");
			setType("String");
			setUniqueMembers(false);
			setLevelType("Regular");
			setHideMemberIf("Never");
		}

		public Boolean getVisible() {
			return visible;
		}
		
		public void setVisible(Boolean visible) {
			this.visible = visible;
		}
		
		/**
         * Gets the value of the annotations property.
         * 
         * @return
         *     possible object is
         *     {@link Annotations }
         *     
         */
        public Annotations getAnnotations() {
            return annotations;
        }

        /**
         * Sets the value of the annotations property.
         * 
         * @param value
         *     allowed object is
         *     {@link Annotations }
         *     
         */
        public void setAnnotations(Annotations value) {
            this.annotations = value;
        }

        /**
         * Gets the value of the keyExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionView }
         *     
         */
        public ExpressionView getKeyExpression() {
            return keyExpression;
        }

        /**
         * Sets the value of the keyExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionView }
         *     
         */
        public void setKeyExpression(ExpressionView value) {
            this.keyExpression = value;
        }

        /**
         * Gets the value of the nameExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionView }
         *     
         */
        public ExpressionView getNameExpression() {
            return nameExpression;
        }

        /**
         * Sets the value of the nameExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionView }
         *     
         */
        public void setNameExpression(ExpressionView value) {
            this.nameExpression = value;
        }

        /**
         * Gets the value of the captionExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionView }
         *     
         */
        public ExpressionView getCaptionExpression() {
            return captionExpression;
        }

        /**
         * Sets the value of the captionExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionView }
         *     
         */
        public void setCaptionExpression(ExpressionView value) {
            this.captionExpression = value;
        }

        /**
         * Gets the value of the ordinalExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionView }
         *     
         */
        public ExpressionView getOrdinalExpression() {
            return ordinalExpression;
        }

        /**
         * Sets the value of the ordinalExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionView }
         *     
         */
        public void setOrdinalExpression(ExpressionView value) {
            this.ordinalExpression = value;
        }

        /**
         * Gets the value of the parentExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionView }
         *     
         */
        public ExpressionView getParentExpression() {
            return parentExpression;
        }

        /**
         * Sets the value of the parentExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionView }
         *     
         */
        public void setParentExpression(ExpressionView value) {
            this.parentExpression = value;
        }

        /**
         * Gets the value of the closure property.
         * 
         * @return
         *     possible object is
         *     {@link Hierarchy.Level.Closure }
         *     
         */
        public Hierarchy.Level.Closure getClosure() {
            return closure;
        }

        /**
         * Sets the value of the closure property.
         * 
         * @param value
         *     allowed object is
         *     {@link Hierarchy.Level.Closure }
         *     
         */
        public void setClosure(Hierarchy.Level.Closure value) {
            this.closure = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Hierarchy.Level.Property }
         * 
         * 
         */
        public List<Hierarchy.Level.Property> getProperty() {
            if (property == null) {
                property = new ArrayList<Hierarchy.Level.Property>();
            }
            return this.property;
        }

        /**
         * Gets the value of the approxRowCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getApproxRowCount() {
            return approxRowCount;
        }

        /**
         * Sets the value of the approxRowCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setApproxRowCount(BigInteger value) {
            this.approxRowCount = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the table property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTable() {
            return table;
        }

        /**
         * Sets the value of the table property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTable(String value) {
            this.table = value;
        }

        /**
         * Gets the value of the column property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColumn() {
            return column;
        }

        /**
         * Sets the value of the column property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColumn(String value) {
            this.column = value;
        }

        /**
         * Gets the value of the nameColumn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameColumn() {
            return nameColumn;
        }

        /**
         * Sets the value of the nameColumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameColumn(String value) {
            this.nameColumn = value;
        }

        /**
         * Gets the value of the ordinalColumn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrdinalColumn() {
            return ordinalColumn;
        }

        /**
         * Sets the value of the ordinalColumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrdinalColumn(String value) {
            this.ordinalColumn = value;
        }

        /**
         * Gets the value of the parentColumn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentColumn() {
            return parentColumn;
        }

        /**
         * Sets the value of the parentColumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentColumn(String value) {
            this.parentColumn = value;
        }

        /**
         * Gets the value of the nullParentValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNullParentValue() {
            return nullParentValue;
        }

        /**
         * Sets the value of the nullParentValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNullParentValue(String value) {
            this.nullParentValue = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the uniqueMembers property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isUniqueMembers() {
            if (uniqueMembers == null) {
                return false;
            } else {
                return uniqueMembers;
            }
        }

        /**
         * Sets the value of the uniqueMembers property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUniqueMembers(Boolean value) {
            this.uniqueMembers = value;
        }

        /**
         * Gets the value of the levelType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLevelType() {
            if (levelType == null) {
                return "Regular";
            } else {
                return levelType;
            }
        }

        /**
         * Sets the value of the levelType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLevelType(String value) {
            this.levelType = value;
        }

        /**
         * Gets the value of the hideMemberIf property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHideMemberIf() {
            if (hideMemberIf == null) {
                return "Never";
            } else {
                return hideMemberIf;
            }
        }

        /**
         * Sets the value of the hideMemberIf property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHideMemberIf(String value) {
            this.hideMemberIf = value;
        }

        /**
         * Gets the value of the formatter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormatter() {
            return formatter;
        }

        /**
         * Sets the value of the formatter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormatter(String value) {
            this.formatter = value;
        }

        /**
         * Gets the value of the caption property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCaption() {
            return caption;
        }

        /**
         * Sets the value of the caption property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCaption(String value) {
            this.caption = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the captionColumn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCaptionColumn() {
            return captionColumn;
        }

        /**
         * Sets the value of the captionColumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCaptionColumn(String value) {
            this.captionColumn = value;
        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "table"
        })
        public static class Closure {

            @XmlElement(name = "Table", required = true)
            protected Table table;
            @XmlAttribute(required = true)
            protected String parentColumn;
            @XmlAttribute(required = true)
            protected String childColumn;

            /**
             * Gets the value of the table property.
             * 
             * @return
             *     possible object is
             *     {@link Table }
             *     
             */
            public Table getTable() {
                return table;
            }

            /**
             * Sets the value of the table property.
             * 
             * @param value
             *     allowed object is
             *     {@link Table }
             *     
             */
            public void setTable(Table value) {
                this.table = value;
            }

            /**
             * Gets the value of the parentColumn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getParentColumn() {
                return parentColumn;
            }

            /**
             * Sets the value of the parentColumn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setParentColumn(String value) {
                this.parentColumn = value;
            }

            /**
             * Gets the value of the childColumn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChildColumn() {
                return childColumn;
            }

            /**
             * Sets the value of the childColumn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChildColumn(String value) {
                this.childColumn = value;
            }

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Property {

            @XmlAttribute(required = true)
            protected String name;
            @XmlAttribute(required = true)
            protected String column;
            @XmlAttribute
            protected String type;
            @XmlAttribute
            protected String formatter;
            @XmlAttribute
            protected String caption;
            @XmlAttribute
            protected String description;
            @XmlAttribute
            protected Boolean dependsOnLevelValue;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the column property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColumn() {
                return column;
            }

            /**
             * Sets the value of the column property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColumn(String value) {
                this.column = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                if (type == null) {
                    return "String";
                } else {
                    return type;
                }
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the formatter property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormatter() {
                return formatter;
            }

            /**
             * Sets the value of the formatter property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormatter(String value) {
                this.formatter = value;
            }

            /**
             * Gets the value of the caption property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCaption() {
                return caption;
            }

            /**
             * Sets the value of the caption property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCaption(String value) {
                this.caption = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the dependsOnLevelValue property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isDependsOnLevelValue() {
                if (dependsOnLevelValue == null) {
                    return false;
                } else {
                    return dependsOnLevelValue;
                }
            }

            /**
             * Sets the value of the dependsOnLevelValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setDependsOnLevelValue(Boolean value) {
                this.dependsOnLevelValue = value;
            }

        }

    }

   
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MemberReaderParameter {

        @XmlAttribute(required = true)
        protected String name;
        @XmlAttribute(required = true)
        protected String value;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
