//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.01 at 03:55:36 PM CET 
//


package org.openforis.calc.olap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.openforis.calc.model.VariableMetadata;


/**
 * 
 *                 Shared dimensions in this schema.
 *                 A Dimension is a collection of hierarchies. There are two kinds: a public
 *                 dimension belongs to a Schema, and be used by several cubes;
 *                 a private dimension belongs to a Cube.
 *                 The foreignKey field is only applicable to private dimensions. 
 *             
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SharedDimension", propOrder = {
    "annotations",
    "hierarchy"
})
public class SharedDimension {

    static final String TYPE_STANDARD_DIMENSION = "StandardDimension";
    
	@XmlElement(name = "Annotations")
    protected List<Annotations> annotations;
    @XmlElement(name = "Hierarchy", required = true)
    protected List<Hierarchy> hierarchy;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected String caption;
    @XmlAttribute
    protected String description;
    @XmlAttribute
    protected Boolean visible;
    @XmlAttribute
    protected Boolean highCardinality;
    
    @XmlTransient
    private VariableMetadata variableMetadata;
    
    public SharedDimension() {
	
	}
    
    public SharedDimension(VariableMetadata variableMetadata) {
    	this.variableMetadata = variableMetadata;
    	setType( TYPE_STANDARD_DIMENSION );
    	setVisible( true );
    	setHighCardinality( false );
    	setName( Schema.getMdxName(variableMetadata.getVariableName()) );
    	getHierarchies().add( new Hierarchy(variableMetadata) );
	}
    
    /**
     * Gets the value of the annotations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Annotations }
     * 
     * 
     */
    public List<Annotations> getAnnotations() {
        if (annotations == null) {
            annotations = new ArrayList<Annotations>();
        }
        return this.annotations;
    }

    /**
     * Gets the value of the hierarchy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hierarchy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHierarchy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hierarchy }
     * 
     * 
     */
    public List<Hierarchy> getHierarchies() {
        if (hierarchy == null) {
            hierarchy = new ArrayList<Hierarchy>();
        }
        return this.hierarchy;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "Standard";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    public Boolean getVisible() {
		return visible;
	}
    
    public void setVisible(Boolean visible) {
		this.visible = visible;
	}

    public Boolean getHighCardinality() {
		return highCardinality;
	}
    
    public void setHighCardinality(Boolean highCardinality) {
		this.highCardinality = highCardinality;
	}
}
