/*
Script generated by Aqua Data Studio 12.0.14 on Dec-30-2012 05:09:23 PM
Database: null
Schema: <All Schemas>
*/

ALTER TABLE "calc"."aoi"
	DROP CONSTRAINT "fk_aoi_parent" CASCADE 
GO

ALTER TABLE "calc"."aoi"
	DROP CONSTRAINT "fk_aoi_hierarchy" CASCADE 
GO

ALTER TABLE "calc"."category"
	DROP CONSTRAINT "fk_category_variable" CASCADE 
GO

ALTER TABLE "calc"."plot_category"
	DROP CONSTRAINT "fk_plot_category_category" CASCADE 
GO

ALTER TABLE "calc"."specimen_category"
	DROP CONSTRAINT "fk_specimen_category_category" CASCADE 
GO

ALTER TABLE "calc"."cluster_category"
	DROP CONSTRAINT "fk_cluster_category_category" CASCADE 
GO

ALTER TABLE "calc"."plot"
	DROP CONSTRAINT "fk_plot_cluster" CASCADE 
GO

ALTER TABLE "calc"."surveyed_cluster"
	DROP CONSTRAINT "fk_surveyed_cluster_cluster" CASCADE 
GO

ALTER TABLE "calc"."category"
	DROP CONSTRAINT "fk_numeric_band_category" CASCADE 
GO

ALTER TABLE "calc"."plot_numeric_value"
	DROP CONSTRAINT "fk_plot_numeric_value_variable" CASCADE 
GO

ALTER TABLE "calc"."specimen_numeric_value"
	DROP CONSTRAINT "fk_specimen_numeric_value_variable" CASCADE 
GO

ALTER TABLE "calc"."cluster_numeric_value"
	DROP CONSTRAINT "fk_cluster_numeric_value_variable" CASCADE 
GO

ALTER TABLE "calc"."numeric_variable_banding"
	DROP CONSTRAINT "fk_banding_numeric_variable" CASCADE 
GO

ALTER TABLE "calc"."numeric_band"
	DROP CONSTRAINT "fk_numeric_band_banding" CASCADE 
GO

ALTER TABLE "calc"."categorical_variable"
	DROP CONSTRAINT "fk_categorical_variable_banding" CASCADE 
GO

ALTER TABLE "calc"."process"
	DROP CONSTRAINT "fk_process_operation" CASCADE 
GO

ALTER TABLE "calc"."surveyed_plot"
	DROP CONSTRAINT "fk_surveyed_plot_plot" CASCADE 
GO

ALTER TABLE "calc"."operation_parameter"
	DROP CONSTRAINT "fk_operation_parameter_process" CASCADE 
GO

ALTER TABLE "calc"."process"
	DROP CONSTRAINT "fk_process_processing_chain" CASCADE 
GO

ALTER TABLE "calc"."specimen_numeric_value"
	DROP CONSTRAINT "fk_specimen_numeric_value_specimen" CASCADE 
GO

ALTER TABLE "calc"."specimen_category"
	DROP CONSTRAINT "fk_specimen_category_specimen" CASCADE 
GO

ALTER TABLE "calc"."plot"
	DROP CONSTRAINT "fk_plot_stratum" CASCADE 
GO

ALTER TABLE "calc"."aoi_hierarchy"
	DROP CONSTRAINT "fk_aoi_hierarchy_survey" CASCADE 
GO

ALTER TABLE "calc"."survey_unit"
	DROP CONSTRAINT "fk_survey_unit_survey" CASCADE 
GO

ALTER TABLE "calc"."processing_chain"
	DROP CONSTRAINT "fk_processing_chain_survey" CASCADE 
GO

ALTER TABLE "calc"."stratum"
	DROP CONSTRAINT "fk_stratum_survey" CASCADE 
GO

ALTER TABLE "calc"."taxonomic_checklist"
	DROP CONSTRAINT "fk_taxonomic_checklist_survey" CASCADE 
GO

ALTER TABLE "calc"."numeric_variable"
	DROP CONSTRAINT "fk_numeric_variable_survey_unit" CASCADE 
GO

ALTER TABLE "calc"."categorical_variable"
	DROP CONSTRAINT "fk_categorical_variable_survey_unit" CASCADE 
GO

ALTER TABLE "calc"."cluster_category"
	DROP CONSTRAINT "fk_cluster_class_value_surveyed" CASCADE 
GO

ALTER TABLE "calc"."cluster_numeric_value"
	DROP CONSTRAINT "fk_cluster_numeric_value_surveyed" CASCADE 
GO

ALTER TABLE "calc"."surveyed_plot"
	DROP CONSTRAINT "fk_surveyed_plot_cluster" CASCADE 
GO

ALTER TABLE "calc"."plot_numeric_value"
	DROP CONSTRAINT "fk_plot_numeric_value_surveyed_plot" CASCADE 
GO

ALTER TABLE "calc"."plot_category"
	DROP CONSTRAINT "fk_plot_category_value_surveyed_plot" CASCADE 
GO

ALTER TABLE "calc"."specimen"
	DROP CONSTRAINT "fk_specimen_plot" CASCADE 
GO

ALTER TABLE "calc"."surveyed_plot"
	DROP CONSTRAINT "fk_parent_surveyed_plot" CASCADE 
GO

ALTER TABLE "calc"."specimen"
	DROP CONSTRAINT "fk_specimen_taxon" CASCADE 
GO

ALTER TABLE "calc"."taxon"
	DROP CONSTRAINT "fk_taxon_accepted_name" CASCADE 
GO

ALTER TABLE "calc"."taxon"
	DROP CONSTRAINT "fk_taxon_original_name" CASCADE 
GO

ALTER TABLE "calc"."taxon"
	DROP CONSTRAINT "fk_taxon_parent" CASCADE 
GO

ALTER TABLE "calc"."taxon_vernacular_name"
	DROP CONSTRAINT "fk_taxon_vernacular_name_accepted_usage" CASCADE 
GO

ALTER TABLE "calc"."taxon"
	DROP CONSTRAINT "fk_taxon_checklist" CASCADE 
GO

ALTER TABLE "calc"."category"
	DROP CONSTRAINT "uk_plot_class_code" CASCADE 
GO

ALTER TABLE "calc"."category"
	DROP CONSTRAINT "uk_plot_class_order" CASCADE 
GO

ALTER TABLE "calc"."numeric_band"
	DROP CONSTRAINT "uk_plot_derived_class_class" CASCADE 
GO

ALTER TABLE "calc"."survey"
	DROP CONSTRAINT "uk_survey_uri" CASCADE 
GO

ALTER TABLE "calc"."surveyed_cluster"
	DROP CONSTRAINT "uk_plot_obs_1" CASCADE 
GO

ALTER TABLE "calc"."surveyed_plot"
	DROP CONSTRAINT "uk_plot_obs" CASCADE 
GO

DROP TABLE "calc"."aoi"
GO

DROP TABLE "calc"."aoi_hierarchy"
GO

DROP TABLE "calc"."categorical_variable"
GO

DROP TABLE "calc"."category"
GO

DROP TABLE "calc"."cluster"
GO

DROP TABLE "calc"."cluster_category"
GO

DROP TABLE "calc"."cluster_numeric_value"
GO

DROP TABLE "calc"."numeric_band"
GO

DROP TABLE "calc"."numeric_variable"
GO

DROP TABLE "calc"."numeric_variable_banding"
GO

DROP TABLE "calc"."operation"
GO

DROP TABLE "calc"."operation_parameter"
GO

DROP TABLE "calc"."plot"
GO

DROP TABLE "calc"."plot_category"
GO

DROP TABLE "calc"."plot_numeric_value"
GO

DROP TABLE "calc"."process"
GO

DROP TABLE "calc"."processing_chain"
GO

DROP TABLE "calc"."specimen"
GO

DROP TABLE "calc"."specimen_category"
GO

DROP TABLE "calc"."specimen_numeric_value"
GO

DROP TABLE "calc"."stratum"
GO

DROP TABLE "calc"."survey"
GO

DROP TABLE "calc"."survey_unit"
GO

DROP TABLE "calc"."surveyed_cluster"
GO

DROP TABLE "calc"."surveyed_plot"
GO

DROP TABLE "calc"."taxon"
GO

DROP TABLE "calc"."taxon_vernacular_name"
GO

DROP TABLE "calc"."taxonomic_checklist"
GO

